"""Qualify compact integers with real SDKs, frozen bytes, and independent failure cases."""
import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("typed_magic", ROOT / "test/typed_magic_languages.py")
typed_magic = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(typed_magic)
examples = typed_magic.examples
FILES = typed_magic.FILES
WSL_CASE_BATCH_SIZE = 64  # Keep JSON arguments below Windows' process command-line limit.

# Each hex payload is an independent wire fixture, never generated by a tested codec.
FIELDS = (
    ("prefix_u8", 255, "40ff"),
    ("prefix_u16", 65535, "80ffff"),
    ("prefix_zero", 0, "00"),
    ("prefix_63", 63, "3f"),
    ("prefix_64", 64, "4040"),
    ("prefix_16383", 16383, "7fff"),
    ("prefix_16384", 16384, "804000"),
    ("prefix_4194303", 4194303, "bfffff"),
    ("prefix_4194304", 4194304, "c0400000"),
    ("prefix_max", 1073741823, "ffffffff"),
    ("lenient_u32", 4294967295, "ffffffff"),
    ("lenient_u64", 18446744073709551615, "ffffffff"),
    ("varint_u8", 255, "ff01"),
    ("varint_u16", 65535, "ffff03"),
    ("varint_zero", 0, "00"),
    ("varint_127", 127, "7f"),
    ("varint_128", 128, "8001"),
    ("varint_16383", 16383, "ff7f"),
    ("varint_16384", 16384, "808001"),
    ("varint_u32_max", 4294967295, "ffffffff0f"),
    ("varint_u64_max", 18446744073709551615, "ffffffffffffffffff01"),
    ("strict_overflow", 0, "00"),
    ("prefix_u64", 1073741823, "ffffffff"),
)


def replace_once(text, old, new):
    """Require reusable consumer snippets to match exactly before adapting them."""
    if text.count(old) != 1:
        raise AssertionError(f"Reusable consumer snippet changed: {old!r}")
    return text.replace(old, new, 1)


def single_consumer(language):
    """Reuse real SDK setup while adding verification and strict writer failure modes."""
    text = typed_magic.consumer(language).replace("TypedMagicRecord", "CompactRecord")
    text = text.replace("typed_magic_record", "compact_record")
    text = text.replace("typed magic", "compact integer").replace("Typed magic", "Compact integer")
    if language in ("javascript", "typescript"):
        protocol = "Number(process.argv[3])" + (" as Protocol" if language == "typescript" else "")
        old = f"try {{ CompactRecord.decode(bytes,{protocol}); }} catch {{ rejected=true; }}"
        new = ("try { const mode=process.argv[2]; "
               f"const value=CompactRecord.decode(bytes,mode==='overflow'?Protocol.JSON:{protocol}); "
               f"if(mode==='overflow') value.encode({protocol}); "
               "else if(mode==='verify') rejected=true; } "
               "catch { rejected=process.argv[2]!=='verify'; }")
        return replace_once(text, old, new)
    if language == "python":
        return replace_once(text,
                            "    try: CompactRecord.decode(Path(sys.argv[3]).read_bytes(),Protocol(int(sys.argv[2])))\n"
                            "    except ValueError: pass\n"
                            "    else: raise AssertionError(\"Invalid compact integer accepted\")",
                            "    mode=sys.argv[1]\n"
                            "    try:\n"
                            "        value=CompactRecord.decode(Path(sys.argv[3]).read_bytes(),Protocol.JSON if mode=='overflow' else Protocol(int(sys.argv[2])))\n"
                            "        if mode=='overflow': value.encode(Protocol(int(sys.argv[2])))\n"
                            "    except ValueError:\n"
                            "        if mode=='verify': raise\n"
                            "    else:\n"
                            "        if mode!='verify': raise AssertionError(\"Invalid compact integer accepted\")")
    if language == "java":
        return replace_once(text,
                            "try { Schema.CompactRecord.decode(bytes,Schema.Protocol.values()[Integer.parseInt(args[1])]); }\n"
                            "      catch(IllegalArgumentException error) { rejected=true; }",
                            "try { var value=Schema.CompactRecord.decode(bytes,args[0].equals(\"overflow\")?Schema.Protocol.JSON:Schema.Protocol.values()[Integer.parseInt(args[1])]);\n"
                            "        if(args[0].equals(\"overflow\"))value.encode(Schema.Protocol.values()[Integer.parseInt(args[1])]);\n"
                            "        else if(args[0].equals(\"verify\"))rejected=true; }\n"
                            "      catch(IllegalArgumentException error) { rejected=!args[0].equals(\"verify\"); }")
    if language == "csharp":
        return replace_once(text,
                            "try { CompactRecord.Decode(bytes,(Protocol)int.Parse(args[1])); } catch(FormatException) { rejected=true; }",
                            "try { var value=CompactRecord.Decode(bytes,args[0]==\"overflow\"?Protocol.JSON:(Protocol)int.Parse(args[1]));\n"
                            "        if(args[0]==\"overflow\")value.Encode((Protocol)int.Parse(args[1]));\n"
                            "        else if(args[0]==\"verify\")rejected=true; } catch(ArgumentException) { rejected=args[0]!=\"verify\"; }\n"
                            "      catch(FormatException) { rejected=args[0]!=\"verify\"; }")
    if language == "go":
        return replace_once(text,
                            'if _,err:=DecodeCompactRecord(data,Protocol(p));err==nil{return fmt.Errorf("Invalid compact integer accepted")}\n    return nil',
                            'protocol:=Protocol(p);if os.Args[1]=="overflow" {protocol=JSON}\n'
                            '    value,err:=DecodeCompactRecord(data,protocol)\n'
                            '    if os.Args[1]=="verify" {return err}\n'
                            '    if err!=nil{return nil}\n'
                            '    if os.Args[1]=="overflow" {if _,err:=value.Encode(Protocol(p));err!=nil{return nil}}\n'
                            '    return fmt.Errorf("Invalid compact integer accepted")')
    if language == "rust":
        return replace_once(text,
                            'assert!(CompactRecord::decode(&bytes,protocols[p]).is_err(),"Invalid compact integer accepted");',
                            'if args[1]=="verify" {CompactRecord::decode(&bytes,protocols[p])?;}\n'
                            '    else if args[1]=="overflow" {assert!(CompactRecord::decode(&bytes,Protocol::Json)?.encode(protocols[p]).is_err());}\n'
                            '    else {assert!(CompactRecord::decode(&bytes,protocols[p]).is_err(),"Invalid compact integer accepted");}')
    if language == "swift":
        return replace_once(text,
                            "do { _ = try CompactRecord.decode(data,Protocol(rawValue:Int(args[2])!)!) } catch { rejected=true }",
                            "do { let value = try CompactRecord.decode(data,args[1]==\"overflow\" ? .JSON : Protocol(rawValue:Int(args[2])!)!)\n"
                            "    if args[1]==\"overflow\" { _ = try value.encode(Protocol(rawValue:Int(args[2])!)!) }\n"
                            "    else if args[1]==\"verify\" { rejected=true }\n"
                            "  } catch { rejected=args[1] != \"verify\" }")
    if language == "kotlin":
        return replace_once(text,
                            "try { CompactRecord.decode(data,Protocol.entries[args[1].toInt()]) } catch(error:IllegalArgumentException) { rejected=true }",
                            "try { val value=CompactRecord.decode(data,if(args[0]==\"overflow\")Protocol.JSON else Protocol.entries[args[1].toInt()])\n"
                            "      if(args[0]==\"overflow\")value.encode(Protocol.entries[args[1].toInt()])\n"
                            "      else if(args[0]==\"verify\")rejected=true\n"
                            "    } catch(error:IllegalArgumentException) { rejected=args[0]!=\"verify\" }")
    if language == "cpp":
        text = replace_once(text, "bool rejects(const std::string& bytes) {\n"
                            "  try { (void)decode<Protocol>(bytes); } catch(const std::exception&) { return true; }return false;\n}",
                            "bool rejects(const std::string& bytes,const std::string& mode) {\n"
                            "  if(mode==\"overflow\") {\n"
                            "    const auto value=decode<rohit::serializer::json>(bytes);\n"
                            "    try { (void)encode<Protocol>(value); } catch(const std::exception&) { return true; }return false;\n"
                            "  }\n"
                            "  try { (void)decode<Protocol>(bytes); return mode==\"verify\"; }\n"
                            "  catch(const std::exception&) { return mode!=\"verify\"; }\n}")
        return text.replace("(bytes)?0:1", "(bytes,argv[1])?0:1")
    if language == "c":
        return replace_once(text,
                            "require(compact_record_decode(&value,bytes,(size_t)size,(srl_protocol)atoi(argv[2]),NULL)!=srl_ok);",
                            "if(strcmp(argv[1],\"overflow\")==0) {\n"
                            "      require(compact_record_decode(&value,bytes,(size_t)size,srl_json,NULL)==srl_ok);\n"
                            "      srl_buffer encoded={0};require(compact_record_encode(&value,(srl_protocol)atoi(argv[2]),&encoded)!=srl_ok);srl_buffer_free(&encoded);\n"
                            "    } else if(strcmp(argv[1],\"verify\")==0) {\n"
                            "      require(compact_record_decode(&value,bytes,(size_t)size,(srl_protocol)atoi(argv[2]),NULL)==srl_ok);\n"
                            "    } else { require(compact_record_decode(&value,bytes,(size_t)size,(srl_protocol)atoi(argv[2]),NULL)!=srl_ok); }")
    raise ValueError(language)


def consumer(language):
    """Batch interpreter and VM cases while creating a fresh codec session for every fixture."""
    text = single_consumer(language)
    if language in ("javascript", "typescript"):
        begin = text.index("if(process.argv.length>4)")
        body = text[begin:].replace("process.argv", "args")
        argument_type = ": string[]" if language == "typescript" else ""
        return (text[:begin] + f"// Run one independent codec case.\nfunction run(args{argument_type}) {{\n" +
                body + "\n}\nconst args=process.argv;\n"
                "if(args[2]==='batch') {\n"
                "  const manifest=new TextDecoder().decode(readFileSync(args[3]));\n"
                "  for(const line of manifest.trimEnd().split(/\\r?\\n/))run([args[0],args[1],...line.split('\\t')]);\n"
                "} else run(args);\n")
    if language == "python":
        begin = text.index("if len(sys.argv)>3:")
        body = text[begin:].replace("sys.argv", "args")
        indented = "\n".join("    " + line for line in body.splitlines())
        return (text[:begin] + "def run(args):\n    \"\"\"Run one independent codec case.\"\"\"\n" +
                indented + "\n\nif len(sys.argv)==3 and sys.argv[1]=='batch':\n"
                "    for line in Path(sys.argv[2]).read_text(encoding='utf-8').splitlines():\n"
                "        run([sys.argv[0],*line.split('\\t')])\n"
                "else: run(sys.argv)\n")
    if language == "java":
        return replace_once(text, "public static void main(String[] args) throws Exception {",
                            "public static void main(String[] args) throws Exception {\n"
                            "    if(args.length==2 && args[0].equals(\"batch\")) {\n"
                            "      for(var line:Files.readAllLines(Path.of(args[1])))main(line.split(\"\\t\",-1));\n"
                            "      return;\n"
                            "    }")
    if language == "csharp":
        return replace_once(text, "private static void Main(string[] args) {",
                            "private static void Main(string[] args) {\n"
                            "    if(args.Length==2 && args[0]==\"batch\") {\n"
                            "      foreach(var line in File.ReadAllLines(args[1]))Main(line.Split('\\t'));\n"
                            "      return;\n"
                            "    }")
    if language == "kotlin":
        return replace_once(text, "fun main(args:Array<String>) {",
                            "fun main(args:Array<String>) {\n"
                            "  if(args.size==2 && args[0]==\"batch\") {\n"
                            "    File(args[1]).forEachLine { main(it.split('\\t').toTypedArray()) };return\n"
                            "  }")
    return text


def wire(protocol, replacements=None):
    """Assemble frozen scalar fixtures with independently specified native framing."""
    replacements = replacements or {}
    payload = bytearray()
    for index, (name, _, hex_value) in enumerate(FIELDS, 1):
        if protocol == 2:
            payload.append(index)  # Every explicit fixture ID fits a one-byte prefix.
        elif protocol == 3:
            encoded = name.encode("utf-8")
            assert len(encoded) <= 63
            payload.append(len(encoded))
            payload.extend(encoded)
        payload.extend(replacements.get(name, bytes.fromhex(hex_value)))
    if protocol != 1:
        payload.append(0)
    return bytes(payload)


def cases():
    """Mutate independent encodings to cover truncation, destination overflow, and framing."""
    mutations = (
        ("prefix_u8", "4100"), ("prefix_u16", "810000"),
        ("varint_u8", "8002"), ("varint_u16", "808004"),
        ("varint_zero", "8000"), ("varint_128", "808000"),
        ("varint_u32_max", "ffffffff10"), ("varint_u32_max", "ffffffff80"),
        ("varint_u64_max", "ffffffffffffffffff02"),
        ("varint_u64_max", "ffffffffffffffffff81"),
    )
    for protocol in (1, 2, 3):
        for name, payload in mutations:
            yield "reject", protocol, wire(protocol, {name: bytes.fromhex(payload)})
        valid = wire(protocol)
        yield "reject", protocol, valid + b"\0"
        # Every strict boundary inside the record must fail complete decoding.
        for size in range(len(valid)):
            yield "reject", protocol, valid[:size]
    record = {name: value for name, value, _ in FIELDS}
    for name, value in (("strict_overflow", 1 << 30), ("prefix_u64", (1 << 64) - 1)):
        overflow = dict(record)
        overflow[name] = value
        for protocol in (1, 2, 3):
            yield "overflow", protocol, json.dumps(overflow).encode("utf-8")
    yield "reject", 0, json.dumps({**record, "varint_u8": 256}).encode("utf-8")


def run_cases(runner, language, executable, queued):
    """Batch explicitly selected WSL consumers without repeated service startup."""
    if language in ("java", "csharp", "kotlin", "javascript", "typescript", "python"):
        directory = queued[0][2].parent
        remote_directory = runner.path(language, directory)
        manifest = directory / f"{language}-manifest.tsv"
        manifest.write_text("".join(f"{mode}\t{protocol}\t{remote_directory}/{path.name}\n"
                                    for mode, protocol, path in queued), encoding="utf-8")
        examples.run([*executable, "batch", runner.path(language, manifest)])
        return
    if language in runner.wsl:
        remote_directory = runner.path(language, queued[0][2].parent)
        remote = [(mode, protocol, remote_directory + "/" + path.name)
                  for mode, protocol, path in queued]
        script = ("import json,subprocess,sys; base=json.loads(sys.argv[1]); "
                  "cases=json.loads(sys.argv[2]); "
                  "[subprocess.run(base+[mode,str(protocol),path],check=True) "
                  "for mode,protocol,path in cases]")
        for begin in range(0, len(remote), WSL_CASE_BATCH_SIZE):
            examples.run(["wsl", "--exec", "python3", "-c", script,
                          json.dumps(executable[2:]),
                          json.dumps(remote[begin:begin + WSL_CASE_BATCH_SIZE])])
    else:
        for mode, protocol, path in queued:
            examples.run([*executable, mode, protocol, runner.path(language, path)])


def main():
    """Generate all outputs, compile real SDK consumers, and compare every binary fixture."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--cpp-library", type=Path)
    parser.add_argument("--build", type=Path, default=ROOT / "out/compact-languages")
    parser.add_argument("--language", default="all")
    parser.add_argument("--wsl-languages", default="")
    args = parser.parse_args()
    args.sanitize = False
    args.compiler = args.compiler.resolve()
    if args.cpp_library:
        args.cpp_library = args.cpp_library.resolve()
    args.build = args.build.resolve()
    languages = list(examples.LANGUAGES if args.language == "all" else args.language.split(","))
    targets = {("js" if language == "javascript" else language):
               args.build / language / examples.OUTPUTS[language] for language in languages}
    if "typescript" in languages and "javascript" not in languages:
        targets["js"] = args.build / "typescript/schema.mjs"
    command = [args.compiler, "--input", ROOT / "test/resources/compact_language.serializer",
               "--language", ",".join(targets), "--cpp.format=false", "--go.package=main",
               "--kotlin.package="]
    for language, destination in targets.items():
        destination.parent.mkdir(parents=True, exist_ok=True)
        command += [f"--{language}.output", destination]
    examples.run(command)
    if "typescript" in languages and "javascript" in languages:
        (args.build / "typescript/schema.mjs").write_bytes(targets["js"].read_bytes())
    runner = examples.Runner(args)
    fixtures = args.build / "fixtures"
    fixtures.mkdir(parents=True, exist_ok=True)
    queued = []
    for index, (mode, protocol, data) in enumerate(cases()):
        path = fixtures / f"invalid-{index}.bin"
        path.write_bytes(data)
        queued.append((mode, protocol, path))
    for protocol in (1, 2, 3):
        path = fixtures / f"frozen-{protocol}.bin"
        path.write_bytes(wire(protocol))
        queued.append(("verify", protocol, path))
    for language in languages:
        directory = args.build / language
        source = args.build / "consumers" / language
        source.mkdir(parents=True, exist_ok=True)
        (source / FILES[language]).write_text(consumer(language), encoding="utf-8")
        executable = runner.build(language, "compact", directory, source)
        output = directory / "result"
        examples.run([*executable, runner.path(language, output)])
        produced = [Path(str(output) + f".{p}").read_bytes() for p in range(4)]
        assert json.loads(produced[0]) == {name: value for name, value, _ in FIELDS}, language
        for protocol in (1, 2, 3):
            assert produced[protocol] == wire(protocol), (language, protocol, "frozen wire mismatch")
        run_cases(runner, language, executable, queued)
        print(f"PASS: {language}, compact boundaries, strict/lenient output, frozen bytes and {len(queued)} decode cases", flush=True)


if __name__ == "__main__":
    main()
