# Verify the generated package accepts older releases only within the same major.
foreach(required IN ITEMS VERSION_FILE VERSION)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "package_version.cmake requires ${required}")
  endif()
endforeach()

# Evaluate the same version file that CMake package discovery loads.
function(check_version requested compatible exact)
  set(PACKAGE_FIND_VERSION "${requested}")
  string(REPLACE "." ";" components "${requested}")
  list(GET components 0 PACKAGE_FIND_VERSION_MAJOR)
  list(GET components 1 PACKAGE_FIND_VERSION_MINOR)
  list(GET components 2 PACKAGE_FIND_VERSION_PATCH)
  include("${VERSION_FILE}")
  if(NOT PACKAGE_VERSION STREQUAL VERSION)
    message(FATAL_ERROR "Package version ${PACKAGE_VERSION} differs from ${VERSION}")
  endif()
  if(compatible AND NOT PACKAGE_VERSION_COMPATIBLE OR
      NOT compatible AND PACKAGE_VERSION_COMPATIBLE)
    message(FATAL_ERROR "Incorrect package compatibility for ${requested}")
  endif()
  if(exact AND NOT PACKAGE_VERSION_EXACT OR NOT exact AND PACKAGE_VERSION_EXACT)
    message(FATAL_ERROR "Incorrect exact-version result for ${requested}")
  endif()
endfunction()

string(REPLACE "." ";" components "${VERSION}")
list(GET components 0 major)
list(GET components 1 minor)
list(GET components 2 patch)
check_version("${VERSION}" TRUE TRUE)

if(minor GREATER 0)
  math(EXPR previous_minor "${minor} - 1")
  check_version("${major}.${previous_minor}.0" TRUE FALSE)
  check_version("${major}.${previous_minor}.1" TRUE FALSE)
endif()
if(patch GREATER 0)
  math(EXPR previous_patch "${patch} - 1")
  check_version("${major}.${minor}.${previous_patch}" TRUE FALSE)
endif()

math(EXPR next_patch "${patch} + 1")
math(EXPR next_minor "${minor} + 1")
math(EXPR next_major "${major} + 1")
check_version("${major}.${minor}.${next_patch}" FALSE FALSE)
check_version("${major}.${next_minor}.0" FALSE FALSE)
check_version("${next_major}.0.0" FALSE FALSE)
if(major GREATER 0)
  math(EXPR previous_major "${major} - 1")
  check_version("${previous_major}.${minor}.${patch}" FALSE FALSE)
endif()
