const assert = require('node:assert/strict');
const path = require('node:path');
const { test } = require('node:test');
const { Navigator } = require('../out/navigator');
const { indexSource, generatedNames, dependencySchemas, cppIncludeAt } = require('../out/navigation_model');

const root = path.resolve('navigation workspace');
const file = name => path.join(root, name);
const banner = '// Generated by Serializer. Do not edit this file manually.\n';

/** Encode the same portable absolute dependency paths emitted by Serializer. */
function escapeDependency(value) {
  return value.replaceAll('\\', '/').replaceAll('$', () => '$$').replace(/[ #:]/g, '\\$&');
}

/** Resolve navigation against a mutable filesystem containing no executable/build APIs. */
function fixture(entries, directories = [], headers) {
  const files = new Map(Object.entries(entries).map(([name, text]) => [file(name), text]));
  let cancelled = false;
  const host = { read: async name => files.get(name), cancelled: () => cancelled,
    files: async () => ({ schemas: [...files.keys()].filter(name => name.endsWith('.serializer')),
      headers: headers ? headers.map(file) : [...files.keys()].filter(name => /\.(hpp|h|hxx)$/.test(name)) }),
    includeDirectories: directories.map(group => group.map(file)) };
  return { files, host, cancel: () => { cancelled = true; },
    resolver: () => new Navigator(host),
    at: (name, word, last = false) => last ? files.get(file(name)).lastIndexOf(word) : files.get(file(name)).indexOf(word) };
}

/** Keep location assertions focused on destination names and selected source spelling. */
function selected(state, targets) {
  return targets.map(target => [path.relative(root, target.file).replaceAll('\\', '/'),
    state.files.get(target.file).slice(target.start, target.end)]);
}

test('schema includes and qualified class references navigate into source and merged output', async () => {
  const state = fixture({
    'request.serializer': 'serializer version 1; include types/account.serializer; namespace app { class request { public data::account owner; }}',
    'types/account.serializer': 'serializer version 1; namespace data { class account {} }',
    'build/request.hpp': banner + 'namespace data { class account {}; } namespace app { class request {}; }',
    'build/request.hpp.d': `${escapeDependency(file('build/request.hpp'))}: ${escapeDependency(file('request.serializer'))} ${escapeDependency(file('types/account.serializer'))}`
  });
  const resolver = state.resolver();
  assert.deepEqual(selected(state, await resolver.schema(file('request.serializer'), state.at('request.serializer', 'types/account'), false)),
    [['types/account.serializer', '']]);
  assert.deepEqual(selected(state, await resolver.schema(file('request.serializer'), state.at('request.serializer', 'types/account'), true)),
    [['build/request.hpp', '']]);
  assert.deepEqual(selected(state, await resolver.schema(file('request.serializer'), state.at('request.serializer', 'data::account'), false)),
    [['types/account.serializer', 'account']]);
  assert.deepEqual(selected(state, await resolver.schema(file('request.serializer'), state.at('request.serializer', 'data::account'), true)),
    [['build/request.hpp', 'account']]);
  assert.deepEqual(selected(state, await resolver.headers(file('types/account.serializer'))), [['build/request.hpp', '']]);
});

test('source navigation works before generation and missing output returns no destination', async () => {
  const state = fixture({ 'account.serializer': 'serializer version 1; class account {}',
    'main.cpp': '#include <account.hpp>\naccount value;' });
  const resolver = state.resolver();
  assert.deepEqual(selected(state, await resolver.cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), false)),
    [['account.serializer', '']]);
  assert.deepEqual(await resolver.cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), true), []);
  assert.deepEqual(await resolver.schema(file('account.serializer'), state.at('account.serializer', 'account'), true), []);
  assert.deepEqual(await resolver.headers(file('account.serializer')), []);
});

test('missing includes, comments, strings, field names and unresolved types yield no declaration', async () => {
  const source = 'serializer version 1; include missing.serializer; class account {} class request { public account account; public unknown other; public string label { "account" }; /* public account fake; */ }';
  const state = fixture({ 'request.serializer': source });
  for (const position of [source.indexOf('missing'), source.indexOf('account;'), source.indexOf('unknown'),
    source.indexOf('account"'), source.indexOf('account fake')]) {
    assert.deepEqual(await state.resolver().schema(file('request.serializer'), position, false), []);
  }
});

test('nearest namespaces, global qualifiers, inheritance and container type positions resolve', async () => {
  const source = 'serializer version 1; class account {} namespace a { class account {} namespace b { class request : public account { public array account list; public map(account) ::account lookup; public union(account = one, ::account = two) choice; } } }';
  const state = fixture({ 'request.serializer': source });
  for (const marker of ['account list', 'account)', 'account = one']) {
    const result = await state.resolver().schema(file('request.serializer'), source.indexOf(marker), false);
    assert.equal(result[0].start, source.indexOf('account {}', source.indexOf('namespace a')));
  }
  assert.equal((await state.resolver().schema(file('request.serializer'), source.indexOf(': public account') + ': public '.length, false))[0].start,
    source.indexOf('account {}', source.indexOf('namespace a')));
  for (const marker of ['::account lookup', '::account = two']) {
    const result = await state.resolver().schema(file('request.serializer'), source.indexOf(marker), false);
    assert.equal(result[0].start, source.indexOf('account'));
  }
});

test('diamond and cyclic includes deduplicate declarations and terminate', async () => {
  const state = fixture({ 'request.serializer': 'serializer version 1; include a.serializer; include b.serializer; class request { public account owner; }',
    'a.serializer': 'serializer version 1; include common.serializer;',
    'b.serializer': 'serializer version 1; include common.serializer;',
    'common.serializer': 'serializer version 1; include request.serializer; class account {}' });
  assert.deepEqual(selected(state, await state.resolver().schema(file('request.serializer'), state.at('request.serializer', 'account'), false)),
    [['common.serializer', 'account']]);
});

test('preserved, snake and Pascal type spellings match namespaces and acronym boundaries', async () => {
  assert.deepEqual(generatedNames('HTTPModels::AccountID'), ['HTTPModels::AccountID', 'http_models::account_id', 'http_models::AccountId']);
  for (const qualified of generatedNames('HTTPModels::AccountID')) {
    const [namespace, name] = qualified.split('::');
    const state = fixture({ 'account.serializer': 'serializer version 1; namespace HTTPModels { class AccountID {} }',
      'build/account.hpp': banner + `namespace ${namespace} { class ${name} {}; }` });
    const resolver = state.resolver();
    assert.deepEqual(selected(state, await resolver.schema(file('account.serializer'), state.at('account.serializer', 'AccountID'), true)),
      [['build/account.hpp', name]]);
    assert.deepEqual(selected(state, await resolver.cppDeclaration(file('build/account.hpp'), state.at('build/account.hpp', name))),
      [['account.serializer', 'AccountID']]);
  }
});

test('depfiles disambiguate duplicate basenames and handle renamed output headers', async () => {
  const state = fixture({ 'left/account.serializer': 'serializer version 1; class account {}',
    'right/account.serializer': 'serializer version 1; class account {}',
    'build/renamed.hpp': banner + 'class account {};',
    'build/renamed.hpp.d': `${escapeDependency(file('build/renamed.hpp'))}: ${escapeDependency(file('right/account.serializer'))}` });
  assert.deepEqual(await state.resolver().headers(file('left/account.serializer')), []);
  assert.deepEqual(selected(state, await state.resolver().cppDeclaration(file('build/renamed.hpp'), state.at('build/renamed.hpp', 'account'))),
    [['right/account.serializer', 'account']]);
});

test('legacy duplicate schemas and multiple generated profiles expose all available choices', async () => {
  const state = fixture({ 'left/account.serializer': 'serializer version 1; class account {}',
    'right/account.serializer': 'serializer version 1; class account {}',
    'build/one/account.hpp': banner + 'class account {};',
    'build/two/account.hpp': banner + 'class Account {};' });
  assert.equal((await state.resolver().headers(file('left/account.serializer'))).length, 2);
  assert.equal((await state.resolver().cppDeclaration(file('build/one/account.hpp'), state.at('build/one/account.hpp', 'account'))).length, 2);
});

test('active output inventory excludes other configurations', async () => {
  const state = fixture({ 'account.serializer': 'serializer version 1; class account {}',
    'debug/account.hpp': banner + 'class account {};', 'release/account.hpp': banner + 'class account {};' }, [], ['debug/account.hpp']);
  assert.deepEqual(selected(state, await state.resolver().headers(file('account.serializer'))), [['debug/account.hpp', '']]);
});

test('C++ include search respects target directories and ordinary-header shadowing', async () => {
  const state = fixture({ 'main.cpp': '#include <account.hpp>', 'account.serializer': 'serializer version 1; class account {}',
    'first/account.hpp': '// Ordinary unrelated header', 'second/account.hpp': banner + 'class account {};' }, [['first', 'second']]);
  assert.deepEqual(await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), true), []);
  state.files.delete(file('first/account.hpp'));
  assert.deepEqual(selected(state, await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), true)),
    [['second/account.hpp', '']]);
});

test('quoted local includes shadow generated outputs and comments/macros are ignored', async () => {
  const state = fixture({ 'main.cpp': '#include "account.hpp"', 'account.hpp': '// local header',
    'account.serializer': 'serializer version 1; class account {}', 'build/account.hpp': banner + 'class account {};' });
  assert.deepEqual(await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), false), []);
  for (const source of ['// #include <account.hpp>', '/*\n#include <account.hpp>\n*/', '#include HEADER',
    'auto text = R"code(\n#include <account.hpp>\n)code";']) {
    assert.equal(cppIncludeAt(source, source.indexOf('account')), undefined);
  }
  assert.equal(cppIncludeAt('#include <account.hpp> // account', 28), undefined);
});

test('dependency parser handles escaped paths and rejects stale target identities', () => {
  const header = file('generated #1$/account.hpp');
  const schema = file('schema #1$/account.serializer');
  const text = `${escapeDependency(header)}: \\\n ${escapeDependency(schema)}\n`;
  assert.deepEqual(dependencySchemas(text, header), [schema]);
  assert.deepEqual(dependencySchemas(text, file('other/account.hpp')), []);
});

test('deleted outputs and edits are reflected by the next request; cancellation yields no results', async () => {
  const state = fixture({ 'account.serializer': 'serializer version 1; class account {}',
    'build/account.hpp': banner + 'class account {};' });
  assert.equal((await state.resolver().headers(file('account.serializer'))).length, 1);
  state.files.delete(file('build/account.hpp'));
  assert.deepEqual(await state.resolver().headers(file('account.serializer')), []);
  state.files.set(file('account.serializer'), 'serializer version 1; class changed {}');
  assert.deepEqual(selected(state, await state.resolver().schema(file('account.serializer'), state.at('account.serializer', 'changed'), false)),
    [['account.serializer', 'changed']]);
  state.cancel();
  assert.deepEqual(await state.resolver().schema(file('account.serializer'), state.at('account.serializer', 'changed'), false), []);
});

test('type indexing skips templates, forward declarations and fake classes inside literals', () => {
  const index = indexSource('namespace one::two { template<class T> class box; class account final { const char* value = "class fake {};"; }; enum class state { ready }; }', false);
  assert.deepEqual(index.symbols.filter(symbol => symbol.definition).map(symbol => symbol.qualified), ['one::two::account', 'one::two::state']);
});

test('existing generated includes open even if their original schema is unavailable', async () => {
  const state = fixture({ 'main.cpp': '#include <account.hpp>', 'build/account.hpp': banner + 'class account {};' });
  assert.deepEqual(selected(state, await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), true)),
    [['build/account.hpp', '']]);
  assert.deepEqual(await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), false), []);
});

test('configured include with missing output can still open an available schema', async () => {
  const state = fixture({ 'main.cpp': '#include <account.hpp>',
    'account.serializer': 'serializer version 1; class account {}' }, [['build']]);
  assert.deepEqual(selected(state, await state.resolver().cppInclude(file('main.cpp'), state.at('main.cpp', 'account'), false)),
    [['account.serializer', '']]);
});

test('storage-mode specializations navigate to real definitions and primary declarations map back', async () => {
  const state = fixture({ 'account.serializer': 'serializer version 1; class AccountRecord view owning {}',
    'build/account.hpp': banner + 'template <mode Mode> class AccountRecord; template<> class AccountRecord<mode::owning> {}; template<> class AccountRecord<mode::view> {};' });
  const results = await state.resolver().schema(file('account.serializer'), state.at('account.serializer', 'AccountRecord'), true);
  assert.equal(results.length, 2);
  assert.deepEqual(selected(state, await state.resolver().cppDeclaration(file('build/account.hpp'), state.at('build/account.hpp', 'AccountRecord'))),
    [['account.serializer', 'AccountRecord']]);
});

test('preserved names that normalize alike remain distinct in both directions', async () => {
  const state = fixture({ 'account.serializer': 'serializer version 1; class AccountRecord {} class account_record {}',
    'build/account.hpp': banner + 'class AccountRecord {}; class account_record {};' });
  for (const name of ['AccountRecord', 'account_record']) {
    assert.deepEqual(selected(state, await state.resolver().schema(file('account.serializer'), state.at('account.serializer', name), true)),
      [['build/account.hpp', name]]);
    assert.deepEqual(selected(state, await state.resolver().cppDeclaration(file('build/account.hpp'), state.at('build/account.hpp', name))),
      [['account.serializer', name]]);
  }
});
