const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const vscode = require('vscode');
const manifest = require('../package.json');

/** Exercise standard navigation commands in VS Code using only already available artifacts. */
async function runSuite() {
  const workspace = vscode.Uri.file(process.env.SERIALIZER_TEST_WORKSPACE).fsPath;
  const banner = '// Generated by Serializer. Do not edit this file manually.\n';
  const input = path.join(workspace, 'request.serializer');
  const common = path.join(workspace, 'types/account.serializer');
  const header = path.join(workspace, 'build/request.hpp');
  const cpp = path.join(workspace, 'main.cpp');
  fs.mkdirSync(path.dirname(common), { recursive: true });
  fs.mkdirSync(path.dirname(header), { recursive: true });
  fs.writeFileSync(input, 'serializer version 1;\ninclude types/account;\nclass request { public data::account owner; }\n');
  fs.writeFileSync(common, 'serializer version 1;\nnamespace data { class account {} }\n');
  fs.writeFileSync(header, banner + 'namespace data { class account {}; }\nclass request {};\n');
  fs.writeFileSync(cpp, '#include "build/request.hpp"\ndata::account value{};\n');
  const escape = value => value.replaceAll('\\', '/').replaceAll('$', () => '$$').replace(/[ #:]/g, '\\$&');
  fs.writeFileSync(`${header}.d`, `${escape(header)}: ${escape(input)} ${escape(common)}\n`);
  const extension = vscode.extensions.getExtension(`${manifest.publisher}.${manifest.name}`);
  await extension.activate();
  assert.equal(vscode.extensions.getExtension('ms-vscode.cmake-tools'), undefined);
  const schema = await vscode.workspace.openTextDocument(input);
  await vscode.window.showTextDocument(schema);
  assert.equal(schema.languageId, 'serializer');

  /** Invoke built-in provider commands and normalize Location/LocationLink results. */
  async function navigate(document, text, definition) {
    const position = document.positionAt(document.getText().indexOf(text));
    const targets = await vscode.commands.executeCommand(definition
      ? 'vscode.executeDefinitionProvider' : 'vscode.executeDeclarationProvider', document.uri, position);
    return targets.map(target => ({ uri: target.uri ?? target.targetUri,
      range: target.range ?? target.targetSelectionRange ?? target.targetRange }));
  }
  for (const word of ['types/account', 'data::account']) {
    const declarations = await navigate(schema, word, false);
    assert.equal(declarations.length, 1, `schema declaration: ${word}`);
    assert.equal(declarations[0].uri.fsPath, common);
    const definitions = await navigate(schema, word, true);
    if (!definitions.length) {
      console.log('Navigation inventory:', (await vscode.workspace.findFiles('**/*.{serializer,hpp,hpp.d}',
        '**/{.git,node_modules,.venv}/**')).map(uri => uri.fsPath));
    }
    assert.equal(definitions.length, 1, `schema definition: ${word}`);
    assert.equal(definitions[0].uri.fsPath, word === 'types/account' ? common : header);
  }

  // Exercise all three actual editor actions on the reported class, including reversed selections.
  const ledger = path.join(workspace, 'ledger.serializer');
  const ledgerHeader = path.join(workspace, 'build/ledger.hpp');
  fs.copyFileSync(path.resolve(__dirname, '../../../example/managed/ledger/ledger.serializer'), ledger);
  fs.writeFileSync(ledgerHeader, banner + 'namespace ledger_example { class ledger {}; }\n');
  fs.writeFileSync(`${ledgerHeader}.d`, `${escape(ledgerHeader)}: ${escape(ledger)}\n`);
  const ledgerDocument = await vscode.workspace.openTextDocument(ledger);
  const classOffset = ledgerDocument.getText().indexOf('class ledger');
  for (const [command, destination] of [
    ['editor.action.revealDeclaration', ledger], ['editor.action.revealDefinition', ledgerHeader],
    ['editor.action.goToTypeDefinition', ledger]
  ]) {
    for (const [startOffset, endOffset] of [[classOffset, classOffset],
      [classOffset, classOffset + 'class ledger'.length],
      [classOffset + 'class '.length, classOffset + 'class ledger'.length]]) {
      const start = ledgerDocument.positionAt(startOffset);
      const end = ledgerDocument.positionAt(endOffset);
      for (const reversed of [false, true]) {
        const editor = await vscode.window.showTextDocument(ledgerDocument);
        editor.selection = reversed ? new vscode.Selection(end, start) : new vscode.Selection(start, end);
        await vscode.commands.executeCommand(command);
        const active = vscode.window.activeTextEditor;
        assert.equal(active.document.uri.fsPath, destination, `${command}, reversed=${reversed}`);
        const word = active.document.getWordRangeAtPosition(active.selection.active);
        assert.equal(word && active.document.getText(word), 'ledger',
          `${command}, reversed=${reversed}, cursor=${JSON.stringify(active.selection.active)}`);
      }
    }
  }

  // Type definition resolves the live source type even when it has no generated representation.
  const renamed = new vscode.WorkspaceEdit();
  const ledgerName = classOffset + 'class '.length;
  renamed.replace(ledgerDocument.uri, new vscode.Range(ledgerDocument.positionAt(ledgerName),
    ledgerDocument.positionAt(ledgerName + 'ledger'.length)), 'unsaved_ledger');
  await vscode.workspace.applyEdit(renamed);
  const typeTargets = await vscode.commands.executeCommand('vscode.executeTypeDefinitionProvider',
    ledgerDocument.uri, ledgerDocument.positionAt(ledgerName + 'unsaved_ledger'.length));
  assert.equal(typeTargets.length, 1);
  assert.equal(typeTargets[0].uri.fsPath, ledger);
  assert.equal(ledgerDocument.getText(typeTargets[0].range), 'unsaved_ledger');
  assert.ok(!fs.readFileSync(ledger, 'utf8').includes('unsaved_ledger'));

  // Reproduce a right-click inside an existing selection: VS Code keeps its active end.
  const complexDirectory = path.join(workspace, 'complex');
  fs.cpSync(path.resolve(__dirname, '../../../example/schemas/complex'), complexDirectory, { recursive: true });
  const complex = await vscode.workspace.openTextDocument(path.join(complexDirectory, 'model.serializer'));
  for (const [name, destination] of [['demo::order', 'sales/order.serializer'],
    ['demo::snapshot', 'analytics/snapshot.serializer'], ['demo::customer', 'people/customer.serializer']]) {
    const start = complex.positionAt(complex.getText().indexOf(name));
    const end = complex.positionAt(complex.getText().indexOf(name) + name.length);
    for (const reversed of [false, true]) {
      const editor = await vscode.window.showTextDocument(complex);
      editor.selection = reversed ? new vscode.Selection(end, start) : new vscode.Selection(start, end);
      await vscode.commands.executeCommand('editor.action.revealDeclaration');
      assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, path.join(complexDirectory, destination));
    }
  }

  // Use the reported schema to exercise all enum type occurrences before and after generation.
  const autosar = path.join(workspace, 'styles/autosar/account.serializer');
  const autosarHeader = path.join(workspace, 'build/autosar_account.hpp');
  fs.mkdirSync(path.dirname(autosar), { recursive: true });
  fs.copyFileSync(path.resolve(__dirname, '../../../example/coding_styles/autosar/account.serializer'), autosar);
  const autosarDocument = await vscode.workspace.openTextDocument(autosar);
  for (const word of ['AccountState {', 'AccountState currentState', 'AccountState::WaitingForReview']) {
    const definitions = await navigate(autosarDocument, word, true);
    assert.equal(definitions.length, 1, `ungenerated enum definition: ${word}`);
    assert.equal(definitions[0].uri.fsPath, autosar);
    assert.equal(autosarDocument.getText(definitions[0].range), 'AccountState');
    assert.equal(definitions[0].range.start.line, 3, 'enum declaration, not its field reference');
    assert.equal((await navigate(autosarDocument, word, false))[0].uri.fsPath, autosar);
  }
  fs.writeFileSync(autosarHeader, banner + 'namespace style_demo { enum class account_state { waiting_for_review, active }; }\n');
  fs.writeFileSync(`${autosarHeader}.d`, `${escape(autosarHeader)}: ${escape(autosar)}\n`);
  const generatedAutosar = await vscode.workspace.openTextDocument(autosarHeader);
  const enumDefinitions = await navigate(autosarDocument, 'AccountState::WaitingForReview', true);
  assert.equal(enumDefinitions.length, 1);
  assert.equal(enumDefinitions[0].uri.fsPath, autosarHeader);
  assert.equal(generatedAutosar.getText(enumDefinitions[0].range), 'account_state');

  await vscode.commands.executeCommand('serializer.openGeneratedHeader', vscode.Uri.file(common));
  assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, header);
  const cppDocument = await vscode.workspace.openTextDocument(cpp);
  assert.equal((await navigate(cppDocument, 'build/request.hpp', false))[0].uri.fsPath, input);
  assert.equal((await navigate(cppDocument, 'build/request.hpp', true))[0].uri.fsPath, header);

  // Model the independent C++ provider without requiring a compiler or changing its behavior.
  const generated = await vscode.workspace.openTextDocument(header);
  const accountOffset = generated.getText().indexOf('account');
  const typeLocation = new vscode.Location(generated.uri, new vscode.Range(
    generated.positionAt(accountOffset), generated.positionAt(accountOffset + 'account'.length)));
  const cppExtension = vscode.extensions.getExtension('ms-vscode.cpptools');
  if (cppExtension) {
    await cppExtension.activate();
    await vscode.window.showTextDocument(cppDocument);
    for (let attempt = 0; attempt < 40; ++attempt) {
      if ((await navigate(cppDocument, 'account value', true)).some(target => target.uri.fsPath === header)) { break; }
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }
  const native = cppExtension ? { dispose() {} } : vscode.languages.registerDefinitionProvider({ language: 'cpp', scheme: 'file' }, {
    provideDefinition(document, position) {
      return document.uri.fsPath === cpp && position.line === 1 ? [typeLocation] : [];
    }
  });
  try {
    const declarations = await navigate(cppDocument, 'account value', false);
    assert.ok(declarations.some(target => target.uri.fsPath === common), 'C++ class resolves to its originating schema');
    assert.equal((await navigate(cppDocument, 'account value', true))[0].uri.fsPath, header);
    const editor = await vscode.window.showTextDocument(cppDocument);
    const position = cppDocument.positionAt(cppDocument.getText().indexOf('account value'));
    editor.selection = new vscode.Selection(position, position);
    await vscode.commands.executeCommand('serializer.goToSchemaDeclaration');
    assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, common);
  } finally { native.dispose(); }

  // Exercise the real built-in TypeScript service, including enum type aliases.
  const portable = path.join(workspace, 'portable');
  fs.mkdirSync(portable);
  const portableSchema = path.join(portable, 'model.serializer');
  const typescript = path.join(portable, 'schema.d.mts');
  const consumer = path.join(portable, 'main.mts');
  fs.writeFileSync(portableSchema, 'serializer version 1; namespace data { enum state { ready } class account {} }');
  fs.writeFileSync(typescript, '// Generated by Serializer. Regenerate from the .serializer schema; do not edit.\n' +
    'export declare const DataState: Readonly<{ Ready: 0 }>;\nexport type DataState = typeof DataState[keyof typeof DataState];\nexport class DataAccount {}\n');
  fs.writeFileSync(path.join(portable, 'outputs.d'), `${escape(typescript)}: ${escape(portableSchema)}\n`);
  fs.writeFileSync(consumer, "import type { DataState, DataAccount } from './schema.mjs';\nlet status: DataState;\nlet account: DataAccount;\n");
  const tsDocument = await vscode.workspace.openTextDocument(consumer);
  await vscode.window.showTextDocument(tsDocument);
  await vscode.extensions.getExtension('vscode.typescript-language-features').activate();
  for (const type of ['DataState;', 'DataAccount;']) {
    let results = [];
    for (let attempt = 0; attempt < 40; ++attempt) {
      results = await navigate(tsDocument, type, false);
      if (results.some(result => result.uri.fsPath === portableSchema)) { break; }
      await new Promise(resolve => setTimeout(resolve, 200));
    }
    assert.ok(results.some(result => result.uri.fsPath === portableSchema), `real TypeScript declaration: ${type}`);
  }

  // Unsaved schema edits participate in declaration navigation and are never saved by it.
  const change = new vscode.WorkspaceEdit();
  change.insert(schema.uri, schema.positionAt(schema.getText().length), '\nclass unsaved {}\n');
  await vscode.workspace.applyEdit(change);
  assert.equal((await navigate(schema, 'unsaved', false))[0].uri.fsPath, input);
  assert.equal((await navigate(schema, 'unsaved', true))[0].uri.fsPath, input);
  assert.equal(schema.isDirty, true);
  assert.ok(!fs.readFileSync(input, 'utf8').includes('unsaved'));
  const missing = path.join(workspace, 'missing.serializer');
  fs.writeFileSync(missing, 'serializer version 1; class missing {}');
  const missingDocument = await vscode.workspace.openTextDocument(missing);
  assert.equal((await navigate(missingDocument, 'missing', true))[0].uri.fsPath, missing);
  await vscode.commands.executeCommand('serializer.openGeneratedHeader', missingDocument.uri);
  assert.equal(fs.existsSync(path.join(workspace, 'build/missing.hpp')), false);
  // Reproduce a real staged Git tab whose contents differ from its working file.
  const repository = path.join(workspace, 'git-index');
  const stagedFile = path.join(repository, 'example/swift/generics/model.serializer');
  const includedFile = path.join(repository, 'example/generics/model.serializer');
  fs.mkdirSync(path.dirname(stagedFile), { recursive: true });
  fs.mkdirSync(path.dirname(includedFile), { recursive: true });
  const snapshot = 'serializer version 1;\ninclude ../../generics/model;\nclass box<T> { public T value; }\n';
  fs.writeFileSync(stagedFile, snapshot);
  fs.writeFileSync(includedFile, 'serializer version 1; class included {}');
  execFileSync('git', ['init', repository]);
  execFileSync('git', ['-C', repository, 'add', '.']);
  fs.writeFileSync(stagedFile, 'serializer version 1; include wrong;');
  const git = await vscode.extensions.getExtension('vscode.git').activate();
  const api = git.getAPI(1);
  const gitRepository = await api.openRepository(vscode.Uri.file(repository));
  assert.ok(gitRepository, 'Git extension opened the staged example repository');
  await gitRepository.status();
  const stagedUri = api.toGitUri(vscode.Uri.file(stagedFile), '~');
  const staged = await vscode.workspace.openTextDocument(stagedUri);
  assert.equal(staged.getText(), snapshot);
  assert.equal(staged.languageId, 'serializer');
  for (const definition of [false, true]) {
    assert.equal((await navigate(staged, '../../generics/model', definition))[0].uri.fsPath, includedFile);
  }
  const stagedEditor = await vscode.window.showTextDocument(staged);
  const includePosition = staged.positionAt(snapshot.indexOf('../../generics/model'));
  stagedEditor.selection = new vscode.Selection(includePosition, includePosition);
  await vscode.commands.executeCommand('editor.action.revealDefinition');
  assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, includedFile);
  const parameters = await vscode.commands.executeCommand('vscode.executeTypeDefinitionProvider',
    stagedUri, staged.positionAt(snapshot.indexOf('T value')));
  assert.equal(parameters[0].uri.toString(), stagedUri.toString());
  assert.equal(staged.offsetAt(parameters[0].range.start), snapshot.indexOf('T>'));
  console.log('Git index navigation passed using the real Git provider and Go to Definition action.');
  console.log('Serializer navigation host passed: native declaration/definition/type definition for ledger keywords and selections in both directions, live schema type definition, complex model selections, real TypeScript class/enum resolution, schema and C++ includes/types, AUTOSAR enum defaults, schema fallback, merged output, ignored build directory, unsaved buffers, missing output, and no CMake/build dependency.');
  if (cppExtension) { console.log(`Verified native Microsoft C/C++ ${cppExtension.packageJSON.version} navigation.`); }
}

/** Fail promptly if a provider deadlocks or unexpectedly displays an interactive prompt. */
exports.run = async function run() {
  let timer;
  try {
    await Promise.race([runSuite(), new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error('Navigation integration test timed out')), 60_000);
    })]);
  } finally { clearTimeout(timer); }
};
