const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { createRequire } = require('node:module');
const { test } = require('node:test');

const root = path.resolve('provider workspace');
const banner = '// Generated by Serializer. Do not edit this file manually.\n';

/** Exercise real provider registration with a filesystem and editor that cannot build or prompt. */
function harness({ trusted = true, active = false, model } = {}) {
  const calls = [];
  const files = new Map();
  const commands = new Map();
  const providers = {};
  const cancellation = { isCancellationRequested: false };
  const folder = { uri: uri(root) };
  const documents = [];
  let version = 0;
  /** Create stable local URIs for fake workspace files. */
  function uri(file) { return { fsPath: path.resolve(file), scheme: 'file', toString: () => `file://${file}` }; }
  /** Provide UTF-16 position conversion like VS Code's text documents. */
  function document(name, languageId) {
    const file = path.resolve(root, name);
    return { uri: uri(file), languageId: languageId ?? (name.endsWith('.serializer') ? 'serializer' : 'cpp'),
      getText: () => files.get(file),
      offsetAt: position => files.get(file).split('\n').slice(0, position.line).reduce((sum, line) => sum + line.length + 1, 0) + position.character,
      positionAt: offset => { const before = files.get(file).slice(0, offset).split('\n'); return { line: before.length - 1, character: before.at(-1).length }; } };
  }
  const disposable = { dispose() {} };
  const vscode = {
    Uri: { file: uri }, FileType: { File: 1 },
    RelativePattern: class { constructor(base, pattern) { this.base = base; this.pattern = pattern; } },
    Range: class { constructor(start, end) { this.start = start; this.end = end; } },
    Location: class { constructor(uri, range) { this.uri = uri; this.range = range; } },
    CancellationTokenSource: class { token = cancellation; dispose() {} },
    extensions: { getExtension: () => {
      calls.push('getExtension');
      return { isActive: active, activate: () => assert.fail('navigation activated CMake Tools'),
        exports: { getApi: () => ({ getProject: async () => ({ codeModel: model,
          getActiveBuildType: async () => 'Debug', buildWithResult: () => assert.fail('navigation built output'),
          configureWithResult: () => assert.fail('navigation configured project') }) }) } };
    } },
    workspace: { isTrusted: trusted, textDocuments: documents, getWorkspaceFolder: () => folder,
      asRelativePath: value => path.relative(root, value.fsPath),
      fs: { stat: async uri => {
        if (!files.has(uri.fsPath)) { throw new Error('missing'); }
        return { type: 1, size: files.get(uri.fsPath).length, mtime: version, ctime: version };
      }, readFile: async uri => Buffer.from(files.get(uri.fsPath)) },
      findFiles: async (pattern, exclude) => {
        assert.equal(exclude, null, 'navigation must bypass hidden build-directory exclusions');
        return [...files.keys()].filter(file => pattern.pattern.endsWith('*.serializer')
          ? file.endsWith('.serializer') : /\.(hpp|h|hxx|hh|java|js|mjs|ts|mts|go|cs|rs|py|swift|kt|d)$/.test(file)).map(uri);
      },
      openTextDocument: async uri => {
        if (!files.has(uri.fsPath)) { throw new Error('missing'); }
        return document(uri.fsPath);
      } },
    window: { showInformationMessage: () => assert.fail('navigation displayed a build prompt'),
      showErrorMessage: () => assert.fail('missing destinations should be silent'),
      showTextDocument: async uri => calls.push(`open:${path.basename(uri.fsPath)}`),
      showQuickPick: async items => { calls.push('pick'); return items[0]; } },
    languages: {
      registerDeclarationProvider: (selector, provider) => { providers.selector = selector; providers.declaration = provider; return disposable; },
      registerDefinitionProvider: (_selector, provider) => { providers.definition = provider; return disposable; }
    },
    commands: { registerCommand: (name, callback) => { commands.set(name, callback); return disposable; },
      executeCommand: async (name, ...args) => {
        assert.equal(name, 'vscode.executeDefinitionProvider');
        calls.push(name);
        return providers.cpp ? providers.cpp(...args) : [];
      } }
  };
  const file = path.resolve(__dirname, '../out/navigation.js');
  const localRequire = createRequire(file);
  const exports = {};
  vm.runInThisContext(`(function(require, exports) { ${fs.readFileSync(file, 'utf8')}\n})`, { filename: file })(
    name => name === 'vscode' ? vscode : localRequire(name), exports);
  exports.registerNavigation({ subscriptions: [] });
  return { calls, files, commands, providers, vscode, document, cancellation,
    put: (name, text) => { files.set(path.resolve(root, name), text); ++version; },
    request: async (name, word, definition) => {
      const doc = document(name);
      const position = doc.positionAt(doc.getText().indexOf(word));
      return definition ? providers.definition.provideDefinition(doc, position, cancellation)
        : providers.declaration.provideDeclaration(doc, position, cancellation);
    } };
}

test('navigation works in Restricted Mode and never accesses build APIs or saves a dirty schema', async () => {
  const state = harness({ trusted: false });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  const doc = state.document('account.serializer');
  state.vscode.workspace.textDocuments.push({ ...doc, isDirty: true, save: () => assert.fail('saved input') });
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
  await state.commands.get('serializer.openGeneratedHeader')(doc.uri);
  assert.deepEqual(state.calls, ['open:account.hpp']);
});

test('inactive CMake Tools remains inactive and absent generated output is silent', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  await state.commands.get('serializer.openGeneratedHeader')(state.document('account.serializer').uri);
  assert.deepEqual(state.calls, ['getExtension', 'getExtension']);
});

test('AUTOSAR enum navigation uses live schema ranges and prefers a matching generated definition', async () => {
  const name = 'example/coding_styles/autosar/account.serializer';
  const source = fs.readFileSync(path.resolve(__dirname, '../../..', name), 'utf8');
  const state = harness({ trusted: false });
  state.put(name, source);
  const doc = state.document(name);
  const expected = doc.positionAt(source.indexOf('AccountState'));
  for (const marker of ['AccountState {', 'AccountState currentState', 'AccountState::WaitingForReview']) {
    const targets = await state.request(name, marker, true);
    assert.equal(targets.length, 1);
    assert.equal(targets[0].uri.fsPath, doc.uri.fsPath);
    assert.deepEqual(targets[0].range.start, expected);
  }
  state.put('build/account.hpp', banner + 'namespace style_demo { enum class account_state { waiting_for_review, active }; }');
  assert.equal((await state.request(name, 'AccountState::WaitingForReview', true))[0].uri.fsPath,
    path.join(root, 'build/account.hpp'));
  assert.deepEqual(state.calls, [], 'navigation needs no CMake activation, commands, builds or prompts');
});

test('C++ resolved type locations map to schema while definition is left to the C++ provider', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  state.put('main.cpp', 'account value{};');
  const header = state.document('build/account.hpp');
  const position = header.positionAt(header.getText().indexOf('class account'));
  state.providers.cpp = () => [{ targetUri: header.uri, targetRange: { start: position, end: position } }];
  const results = await state.request('main.cpp', 'account', false);
  assert.equal(results.length, 1);
  assert.equal(path.basename(results[0].uri.fsPath), 'account.serializer');
  assert.deepEqual(await state.request('main.cpp', 'account', true), []);
  assert.equal(state.calls.filter(call => call === 'vscode.executeDefinitionProvider').length, 1);
});

test('active CMake configuration isolates outputs without configuring or building', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [{
    sourceDirectory: root, targets: [{ name: 'app', fileGroups: [
      { isGenerated: true, sources: ['debug/account.hpp'] }
    ] }] }] }] } });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('debug/account.hpp', banner + 'class account {};');
  state.put('release/account.hpp', banner + 'class account {};');
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'debug/account.hpp'));
});

test('disk cache observes changes and missing destinations do not offer generation', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
  state.put('build/account.hpp', banner + '\n\nclass account {};');
  assert.equal((await state.request('account.serializer', 'account', true))[0].range.start.line, 3);
  state.files.delete(path.join(root, 'build/account.hpp'));
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  assert.ok(state.calls.every(call => call === 'getExtension'));
});

test('a missing configured type falls back to its schema instead of another output profile', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [{
    sourceDirectory: root, targets: [{ name: 'app', fileGroups: [
      { isGenerated: true, sources: ['debug/account.hpp'] }
    ] }] }] }] } });
  state.put('account.serializer', 'serializer version 1; enum state { ready } class account { public state value { state::ready }; }');
  state.put('debug/account.hpp', banner + 'class account {};');
  state.put('release/account.hpp', banner + 'enum class state { ready }; class account {};');
  const targets = await state.request('account.serializer', 'state::ready', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  assert.ok(state.calls.every(call => call === 'getExtension'));
});

test('an active CMake model without registered outputs still finds available workspace headers', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [] }] } });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
});

test('schema declarations never wait for CMake and accept the end of a qualified selection', async () => {
  const state = harness({ active: true });
  state.put('model.serializer', 'serializer version 1; include types/order; class model { public array demo::order orders; }');
  state.put('types/order.serializer', 'serializer version 1; namespace demo { class order {} }');
  const document = state.document('model.serializer');
  const position = document.positionAt(document.getText().indexOf('demo::order') + 'demo::order'.length);
  const targets = await state.providers.declaration.provideDeclaration(document, position, state.cancellation);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'types/order.serializer'));
  assert.deepEqual(state.calls, []);
  state.vscode.window.activeTextEditor = { document, selection: { active: position, start: position } };
  await state.commands.get('serializer.goToSchemaDeclaration')();
  assert.deepEqual(state.calls, ['open:order.serializer']);
});

test('all generated languages register declarations and honor multi-output dependency files', async () => {
  const samples = [
    ['java', 'Schema.java', '// Generated by Serializer. Requires Java 17 or newer.\nclass Schema { class Demo { class Order {} } }', 'Order'],
    ['javascript', 'schema.mjs', 'export class DemoOrder {}', 'DemoOrder'],
    ['typescript', 'schema.d.mts', 'export class DemoOrder {}', 'DemoOrder'],
    ['go', 'schema.go', 'type DemoOrder struct {}', 'DemoOrder'],
    ['csharp', 'Schema.cs', 'public class Schema { public class DemoOrder {} }', 'DemoOrder'],
    ['rust', 'schema.rs', 'pub struct DemoOrder {}', 'DemoOrder'],
    ['python', 'schema.py', 'class DemoOrder:\n    pass', 'DemoOrder'],
    ['swift', 'Schema.swift', 'public struct DemoOrder {}', 'DemoOrder'],
    ['kotlin', 'Schema.kt', 'class DemoOrder {}', 'DemoOrder'],
    ['c', 'schema.h', '#define SRL_NATIVE_RUNTIME_INCLUDED\ntypedef struct demo_order demo_order;\nstruct demo_order {};', 'demo_order']
  ];
  const state = harness({ trusted: false });
  state.put('model.serializer', 'serializer version 1; include sales/order;');
  state.put('sales/order.serializer', 'serializer version 1; namespace demo { class order {} }');
  const escape = value => path.join(root, value).replaceAll('\\', '/').replace(/[ #:]/g, '\\$&');
  for (const [, name, source] of samples) { state.put(`build/${name}`, source); }
  state.put('build/model.d', `${samples.map(([, name]) => escape(`build/${name}`)).join(' ')}: ${escape('model.serializer')} ${escape('sales/order.serializer')}`);
  for (const [language, name, , type] of samples) {
    assert.ok(state.providers.selector.some(selector => selector.language === language));
    const output = state.document(`build/${name}`, language);
    const position = output.positionAt(output.getText().indexOf(type));
    const location = new state.vscode.Location(output.uri, new state.vscode.Range(position, position));
    state.providers.cpp = () => [location, location];
    state.put(`consumer.${language}`, `${type} value`);
    const consumer = state.document(`consumer.${language}`, language);
    const results = await state.providers.declaration.provideDeclaration(consumer, { line: 0, character: 0 }, state.cancellation);
    assert.equal(results.length, 1, language);
    assert.equal(results[0].uri.fsPath, path.join(root, 'sales/order.serializer'), language);
  }
  const schema = state.document('sales/order.serializer');
  const definitions = await state.providers.definition.provideDefinition(schema,
    schema.positionAt(schema.getText().indexOf('order')), state.cancellation);
  assert.equal(definitions.length, samples.length);
});

test('manifest uses native declaration menus and activates every supported language', () => {
  const manifest = require('../package.json');
  const state = harness();
  for (const { language } of state.providers.selector) {
    if (language !== 'serializer') { assert.ok(manifest.activationEvents.includes(`onLanguage:${language}`), language); }
  }
  assert.ok(!manifest.contributes.menus['editor/context'].some(item => item.command === 'serializer.goToSchemaDeclaration'));
  assert.ok(manifest.contributes.commands.some(item => item.command === 'serializer.goToSchemaDeclaration'));
});
