const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { createRequire } = require('node:module');
const { test } = require('node:test');

const root = path.resolve('provider workspace');
const banner = '// Generated by Serializer. Do not edit this file manually.\n';

/** Exercise real provider registration with a filesystem and editor that cannot build or prompt. */
function harness({ trusted = true, active = false, model } = {}) {
  const calls = [];
  const files = new Map();
  const commands = new Map();
  const providers = {};
  const cancellation = { isCancellationRequested: false };
  const folder = { uri: uri(root) };
  const documents = [];
  let version = 0;
  /** Create stable local URIs for fake workspace files. */
  function uri(file) { return { fsPath: path.resolve(file), scheme: 'file', toString: () => `file://${file}` }; }
  /** Provide UTF-16 position conversion like VS Code's text documents. */
  function document(name, languageId) {
    const file = path.resolve(root, name);
    return { uri: uri(file), languageId: languageId ?? (name.endsWith('.serializer') ? 'serializer' : 'cpp'),
      getText: () => files.get(file),
      offsetAt: position => files.get(file).split('\n').slice(0, position.line).reduce((sum, line) => sum + line.length + 1, 0) + position.character,
      positionAt: offset => { const before = files.get(file).slice(0, offset).split('\n'); return { line: before.length - 1, character: before.at(-1).length }; } };
  }
  const disposable = { dispose() {} };
  const vscode = {
    Uri: { file: uri }, FileType: { File: 1 },
    RelativePattern: class { constructor(base, pattern) { this.base = base; this.pattern = pattern; } },
    Range: class { constructor(start, end) { this.start = start; this.end = end; } },
    Location: class { constructor(uri, range) { this.uri = uri; this.range = range; } },
    CancellationTokenSource: class { token = cancellation; dispose() {} },
    extensions: { getExtension: () => {
      calls.push('getExtension');
      return { isActive: active, activate: () => assert.fail('navigation activated CMake Tools'),
        exports: { getApi: () => ({ getProject: async () => ({ codeModel: model,
          getActiveBuildType: async () => 'Debug', buildWithResult: () => assert.fail('navigation built output'),
          configureWithResult: () => assert.fail('navigation configured project') }) }) } };
    } },
    workspace: { isTrusted: trusted, textDocuments: documents, getWorkspaceFolder: () => folder,
      asRelativePath: value => path.relative(root, value.fsPath),
      fs: { stat: async uri => {
        if (!files.has(uri.fsPath)) { throw new Error('missing'); }
        return { type: 1, size: files.get(uri.fsPath).length, mtime: version, ctime: version };
      }, readFile: async uri => Buffer.from(files.get(uri.fsPath)) },
      findFiles: async (pattern, exclude) => {
        assert.equal(exclude, null, 'navigation must bypass hidden build-directory exclusions');
        return [...files.keys()].filter(file => pattern.pattern.endsWith('*.serializer')
          ? file.endsWith('.serializer') : /\.(hpp|h|hxx|hh|java|js|mjs|ts|mts|go|cs|rs|py|swift|kt|d)$/.test(file)).map(uri);
      },
      openTextDocument: async uri => {
        if (!files.has(uri.fsPath)) { throw new Error('missing'); }
        return document(uri.fsPath);
      } },
    window: { showInformationMessage: () => assert.fail('navigation displayed a build prompt'),
      showErrorMessage: () => assert.fail('missing destinations should be silent'),
      showTextDocument: async uri => calls.push(`open:${path.basename(uri.fsPath)}`),
      showQuickPick: async items => { calls.push('pick'); return items[0]; } },
    languages: {
      registerDeclarationProvider: (selector, provider) => { providers.selector = selector; providers.declaration = provider; return disposable; },
      registerDefinitionProvider: (selector, provider) => { providers.definitionSelector = selector; providers.definition = provider; return disposable; },
      registerTypeDefinitionProvider: (selector, provider) => { providers.typeSelector = selector; providers.typeDefinition = provider; return disposable; }
    },
    commands: { registerCommand: (name, callback) => { commands.set(name, callback); return disposable; },
      executeCommand: async (name, ...args) => {
        assert.ok(['vscode.executeDefinitionProvider', 'vscode.executeTypeDefinitionProvider'].includes(name));
        calls.push(name);
        const resolve = name === 'vscode.executeDefinitionProvider' ? providers.cpp : providers.type;
        return resolve ? resolve(...args) : [];
      } }
  };
  const file = path.resolve(__dirname, '../out/navigation.js');
  const localRequire = createRequire(file);
  const exports = {};
  vm.runInThisContext(`(function(require, exports) { ${fs.readFileSync(file, 'utf8')}\n})`, { filename: file })(
    name => name === 'vscode' ? vscode : localRequire(name), exports);
  exports.registerNavigation({ subscriptions: [] });
  return { calls, files, commands, providers, vscode, document, cancellation,
    put: (name, text) => { files.set(path.resolve(root, name), text); ++version; },
    request: async (name, word, definition) => {
      const doc = document(name);
      const position = doc.positionAt(doc.getText().indexOf(word));
      return definition ? providers.definition.provideDefinition(doc, position, cancellation)
        : providers.declaration.provideDeclaration(doc, position, cancellation);
    } };
}

test('navigation works in Restricted Mode and never accesses build APIs or saves a dirty schema', async () => {
  const state = harness({ trusted: false });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  const doc = state.document('account.serializer');
  state.vscode.workspace.textDocuments.push({ ...doc, isDirty: true, save: () => assert.fail('saved input') });
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
  await state.commands.get('serializer.openGeneratedHeader')(doc.uri);
  assert.deepEqual(state.calls, ['open:account.hpp']);
});

test('ledger declaration, definition and type definition accept names, keywords and selection endpoints', async () => {
  const state = harness({ active: true });
  const source = fs.readFileSync(path.resolve(__dirname, '../../../example/managed/ledger/ledger.serializer'), 'utf8');
  state.put('ledger.serializer', source);
  state.put('build/ledger.hpp', banner + 'namespace ledger_example { class ledger {}; }');
  const document = state.document('ledger.serializer');
  const name = source.indexOf('class ledger') + 'class '.length;
  const offsets = new Set([source.indexOf('class ledger'), source.indexOf('class ledger') + 'class'.length]);
  for (let offset = name; offset <= name + 'ledger'.length; ++offset) { offsets.add(offset); }
  for (const offset of offsets) {
    const position = document.positionAt(offset);
    for (const [provider, method, generated] of [
      ['declaration', 'provideDeclaration', false], ['definition', 'provideDefinition', true],
      ['typeDefinition', 'provideTypeDefinition', false]
    ]) {
      const targets = await state.providers[provider][method](document, position, state.cancellation);
      assert.equal(targets.length, 1, `${provider} at ${offset}`);
      assert.equal(targets[0].uri.fsPath, path.join(root, generated ? 'build/ledger.hpp' : 'ledger.serializer'));
      const target = state.document(targets[0].uri.fsPath);
      assert.equal(target.getText().slice(target.offsetAt(targets[0].range.start), target.offsetAt(targets[0].range.end)), 'ledger');
    }
  }
  assert.deepEqual(state.providers.typeSelector, ['file', 'git'].map(scheme => ({ language: 'serializer', scheme })),
    'native generated-language type providers remain in charge');
});

test('schema type definition follows live transitive qualified types without CMake or output', async () => {
  const state = harness({ active: true });
  state.put('root.serializer', 'serializer version 1; include middle; class root { public demo::renamed value; }');
  state.put('middle.serializer', 'serializer version 1; include types;');
  state.put('types.serializer', 'serializer version 1; namespace demo { class original {} }');
  const original = state.document('types.serializer');
  const liveText = original.getText().replace('original', 'renamed');
  state.vscode.workspace.textDocuments.push({ ...original, getText: () => liveText,
    save: () => assert.fail('type navigation saved an unsaved schema') });
  const document = state.document('root.serializer');
  const start = document.getText().indexOf('demo::renamed');
  for (let offset = start; offset <= start + 'demo::renamed'.length; ++offset) {
    const targets = await state.providers.typeDefinition.provideTypeDefinition(document,
      document.positionAt(offset), state.cancellation);
    assert.equal(targets.length, 1);
    assert.equal(targets[0].uri.fsPath, original.uri.fsPath);
    assert.equal(targets[0].range.start.character, liveText.indexOf('renamed'));
  }
  assert.deepEqual(state.calls, []);
  state.cancellation.isCancellationRequested = true;
  assert.deepEqual(await state.providers.typeDefinition.provideTypeDefinition(document,
    document.positionAt(start), state.cancellation), []);
});

test('inactive CMake Tools remains inactive and absent generated output is silent', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  await state.commands.get('serializer.openGeneratedHeader')(state.document('account.serializer').uri);
  assert.deepEqual(state.calls, ['getExtension', 'getExtension']);
});

test('AUTOSAR enum navigation uses live schema ranges and prefers a matching generated definition', async () => {
  const name = 'example/coding_styles/autosar/account.serializer';
  const source = fs.readFileSync(path.resolve(__dirname, '../../..', name), 'utf8');
  const state = harness({ trusted: false });
  state.put(name, source);
  const doc = state.document(name);
  const expected = doc.positionAt(source.indexOf('AccountState'));
  for (const marker of ['AccountState {', 'AccountState currentState', 'AccountState::WaitingForReview']) {
    const targets = await state.request(name, marker, true);
    assert.equal(targets.length, 1);
    assert.equal(targets[0].uri.fsPath, doc.uri.fsPath);
    assert.deepEqual(targets[0].range.start, expected);
  }
  state.put('build/account.hpp', banner + 'namespace style_demo { enum class account_state { waiting_for_review, active }; }');
  assert.equal((await state.request(name, 'AccountState::WaitingForReview', true))[0].uri.fsPath,
    path.join(root, 'build/account.hpp'));
  assert.deepEqual(state.calls, [], 'navigation needs no CMake activation, commands, builds or prompts');
});

test('C++ resolved type locations map to schema while definition is left to the C++ provider', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  state.put('main.cpp', 'account value{};');
  const header = state.document('build/account.hpp');
  const position = header.positionAt(header.getText().indexOf('class account'));
  state.providers.cpp = () => [{ targetUri: header.uri, targetRange: { start: position, end: position } }];
  const results = await state.request('main.cpp', 'account', false);
  assert.equal(results.length, 1);
  assert.equal(path.basename(results[0].uri.fsPath), 'account.serializer');
  assert.deepEqual(await state.request('main.cpp', 'account', true), []);
  assert.equal(state.calls.filter(call => call === 'vscode.executeDefinitionProvider').length, 1);
});

test('active CMake configuration isolates outputs without configuring or building', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [{
    sourceDirectory: root, targets: [{ name: 'app', fileGroups: [
      { isGenerated: true, sources: ['debug/account.hpp'] }
    ] }] }] }] } });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('debug/account.hpp', banner + 'class account {};');
  state.put('release/account.hpp', banner + 'class account {};');
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'debug/account.hpp'));
});

test('disk cache observes changes and missing destinations do not offer generation', async () => {
  const state = harness();
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
  state.put('build/account.hpp', banner + '\n\nclass account {};');
  assert.equal((await state.request('account.serializer', 'account', true))[0].range.start.line, 3);
  state.files.delete(path.join(root, 'build/account.hpp'));
  const targets = await state.request('account.serializer', 'account', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  assert.ok(state.calls.every(call => call === 'getExtension'));
});

test('a missing configured type falls back to its schema instead of another output profile', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [{
    sourceDirectory: root, targets: [{ name: 'app', fileGroups: [
      { isGenerated: true, sources: ['debug/account.hpp'] }
    ] }] }] }] } });
  state.put('account.serializer', 'serializer version 1; enum state { ready } class account { public state value { state::ready }; }');
  state.put('debug/account.hpp', banner + 'class account {};');
  state.put('release/account.hpp', banner + 'enum class state { ready }; class account {};');
  const targets = await state.request('account.serializer', 'state::ready', true);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'account.serializer'));
  assert.ok(state.calls.every(call => call === 'getExtension'));
});

test('an active CMake model without registered outputs still finds available workspace headers', async () => {
  const state = harness({ active: true, model: { configurations: [{ name: 'Debug', projects: [] }] } });
  state.put('account.serializer', 'serializer version 1; class account {}');
  state.put('build/account.hpp', banner + 'class account {};');
  assert.equal((await state.request('account.serializer', 'account', true)).length, 1);
});

test('schema declarations never wait for CMake and accept the end of a qualified selection', async () => {
  const state = harness({ active: true });
  state.put('model.serializer', 'serializer version 1; include types/order; class model { public array demo::order orders; }');
  state.put('types/order.serializer', 'serializer version 1; namespace demo { class order {} }');
  const document = state.document('model.serializer');
  const position = document.positionAt(document.getText().indexOf('demo::order') + 'demo::order'.length);
  const targets = await state.providers.declaration.provideDeclaration(document, position, state.cancellation);
  assert.equal(targets[0].uri.fsPath, path.join(root, 'types/order.serializer'));
  assert.deepEqual(state.calls, []);
  state.vscode.window.activeTextEditor = { document, selection: { active: position, start: position } };
  await state.commands.get('serializer.goToSchemaDeclaration')();
  assert.deepEqual(state.calls, ['open:order.serializer']);
});

test('all generated languages register declarations and honor multi-output dependency files', async () => {
  const samples = [
    ['java', 'Schema.java', '// Generated by Serializer. Requires Java 17 or newer.\nclass Schema { class Demo { class Order {} } }', 'Order'],
    ['javascript', 'schema.mjs', 'export class DemoOrder {}', 'DemoOrder'],
    ['typescript', 'schema.d.mts', 'export class DemoOrder {}', 'DemoOrder'],
    ['go', 'schema.go', 'type DemoOrder struct {}', 'DemoOrder'],
    ['csharp', 'Schema.cs', 'public class Schema { public class DemoOrder {} }', 'DemoOrder'],
    ['rust', 'schema.rs', 'pub struct DemoOrder {}', 'DemoOrder'],
    ['python', 'schema.py', 'class DemoOrder:\n    pass', 'DemoOrder'],
    ['swift', 'Schema.swift', 'public struct DemoOrder {}', 'DemoOrder'],
    ['kotlin', 'Schema.kt', 'class DemoOrder {}', 'DemoOrder'],
    ['c', 'schema.h', '#define SRL_NATIVE_RUNTIME_INCLUDED\ntypedef struct demo_order demo_order;\nstruct demo_order {};', 'demo_order']
  ];
  const state = harness({ trusted: false });
  state.put('model.serializer', 'serializer version 1; include sales/order;');
  state.put('sales/order.serializer', 'serializer version 1; namespace demo { class order {} }');
  const escape = value => path.join(root, value).replaceAll('\\', '/').replace(/[ #:]/g, '\\$&');
  for (const [, name, source] of samples) { state.put(`build/${name}`, source); }
  state.put('build/model.d', `${samples.map(([, name]) => escape(`build/${name}`)).join(' ')}: ${escape('model.serializer')} ${escape('sales/order.serializer')}`);
  for (const [language, name, , type] of samples) {
    assert.ok(state.providers.selector.some(selector => selector.language === language));
    const output = state.document(`build/${name}`, language);
    const position = output.positionAt(output.getText().indexOf(type));
    const location = new state.vscode.Location(output.uri, new state.vscode.Range(position, position));
    state.providers.cpp = () => [location, location];
    state.put(`consumer.${language}`, `${type} value`);
    const consumer = state.document(`consumer.${language}`, language);
    const results = await state.providers.declaration.provideDeclaration(consumer, { line: 0, character: 0 }, state.cancellation);
    assert.equal(results.length, 1, language);
    assert.equal(results[0].uri.fsPath, path.join(root, 'sales/order.serializer'), language);
  }
  const schema = state.document('sales/order.serializer');
  const definitions = await state.providers.definition.provideDefinition(schema,
    schema.positionAt(schema.getText().indexOf('order')), state.cancellation);
  assert.equal(definitions.length, samples.length);
});

test('manifest uses native declaration menus and activates every supported language', () => {
  const manifest = require('../package.json');
  const state = harness();
  for (const { language } of state.providers.selector) {
    if (language !== 'serializer') { assert.ok(manifest.activationEvents.includes(`onLanguage:${language}`), language); }
  }
  assert.ok(!manifest.contributes.menus['editor/context'].some(item => item.command === 'serializer.goToSchemaDeclaration'));
  assert.ok(manifest.contributes.commands.some(item => item.command === 'serializer.goToSchemaDeclaration'));
});

test('caller mappings use the resolved header owner despite duplicate qualified names and aliases', async () => {
  const state = harness();
  const escape = value => path.join(root, value).replaceAll('\\', '/').replace(/[ #:]/g, '\\$&');
  for (const profile of ['direct', 'collaboration']) {
    state.put(`${profile}/ledger.serializer`, 'serializer version 1; namespace ledger_example { class ledger {} }');
    state.put(`build/${profile}/ledger.hpp`, banner + 'namespace ledger_example { class ledger {}; }');
    state.put(`build/${profile}/ledger.hpp.d`, `${escape(`build/${profile}/ledger.hpp`)}: ${escape(`${profile}/ledger.serializer`)}`);
    state.put(`${profile}.cpp`, 'using ledger = ledger_example::ledger;');
    const header = state.document(`build/${profile}/ledger.hpp`);
    const start = header.positionAt(header.getText().indexOf('class ledger'));
    const end = header.positionAt(header.getText().indexOf('class ledger') + 'class ledger'.length);
    state.providers.cpp = () => [{ targetUri: header.uri, targetRange: { start, end } }];
    const document = state.document(`${profile}.cpp`);
    const first = document.getText().lastIndexOf('ledger');
    for (let offset = first; offset <= first + 'ledger'.length; ++offset) {
      const targets = await state.providers.declaration.provideDeclaration(document, document.positionAt(offset), state.cancellation);
      assert.deepEqual(targets.map(target => target.uri.fsPath), [path.join(root, profile, 'ledger.serializer')]);
    }
  }
});

test('unresolved aliases and unrelated native symbols never guess a schema by spelling', async () => {
  const state = harness();
  state.put('ledger.serializer', 'serializer version 1; class ledger {}');
  state.put('build/ledger.hpp', banner + 'class ledger {};');
  state.put('main.cpp', 'using ledger = missing::ledger; ledger value;');
  state.put('other.cpp', 'using ledger = other::ledger;');
  state.put('ordinary.hpp', 'class ledger {};');
  const document = state.document('main.cpp');
  for (const file of ['main.cpp', 'other.cpp', 'ordinary.hpp']) {
    const target = state.document(file);
    const position = target.positionAt(target.getText().indexOf('ledger'));
    state.providers.cpp = () => [new state.vscode.Location(target.uri, new state.vscode.Range(position, position))];
    assert.deepEqual(await state.request('main.cpp', 'ledger', false), [], file);
  }
  for (const result of [[], undefined, [{ targetUri: { scheme: 'untitled' } }]]) {
    state.providers.cpp = () => result;
    assert.deepEqual(await state.request('main.cpp', 'ledger', false), []);
  }
  state.providers.cpp = () => assert.fail('cancelled navigation reached another provider');
  state.cancellation.isCancellationRequested = true;
  assert.deepEqual(await state.providers.declaration.provideDeclaration(document, { line: 0, character: 0 }, state.cancellation), []);
});

test('stale or deleted schema metadata cannot silently choose another ledger schema', async () => {
  const state = harness();
  const escape = value => path.join(root, value).replaceAll('\\', '/').replace(/[ #:]/g, '\\$&');
  state.put('ledger.serializer', 'serializer version 1; class ledger {}');
  state.put('build/ledger.hpp', banner + 'class ledger {};');
  state.put('main.cpp', 'ledger value;');
  const header = state.document('build/ledger.hpp');
  const position = header.positionAt(header.getText().indexOf('ledger'));
  state.providers.cpp = () => [{ uri: header.uri, range: { start: position, end: position } }];
  for (const depfile of [`${escape('build/ledger.hpp')}: ${escape('old/ledger.serializer')}`,
    `${escape('old/ledger.hpp')}: ${escape('ledger.serializer')}`, 'invalid metadata']) {
    state.put('build/ledger.hpp.d', depfile);
    assert.deepEqual(await state.request('main.cpp', 'ledger', false), [], depfile);
  }
  state.put('build/ledger.hpp.d', `${escape('build/ledger.hpp')}: ${escape('ledger.serializer')}`);
  assert.equal((await state.request('main.cpp', 'ledger', false)).length, 1);
  state.files.delete(header.uri.fsPath);
  assert.deepEqual(await state.request('main.cpp', 'ledger', false), []);
});

test('CRLF and UTF-16 offsets preserve live schema and generated selection ranges', async () => {
  const state = harness();
  state.put('ledger.serializer', '// \u{1f4d2}\r\nserializer version 1;\r\nnamespace demo {\r\n  class ledger {}\r\n}\r\n');
  state.put('build/ledger.hpp', banner + '// \u{1f4d2}\r\nnamespace demo {\r\nclass ledger {};\r\n}\r\n');
  for (const [file, provider, method, expected] of [
    ['ledger.serializer', 'definition', 'provideDefinition', 'build/ledger.hpp'],
    ['build/ledger.hpp', 'declaration', 'provideDeclaration', 'ledger.serializer']
  ]) {
    const document = state.document(file);
    const offset = document.getText().indexOf('ledger');
    for (let index = offset; index <= offset + 'ledger'.length; ++index) {
      const results = await state.providers[provider][method](document, document.positionAt(index), state.cancellation);
      assert.equal(results.length, 1);
      const target = state.document(expected);
      assert.equal(results[0].uri.fsPath, target.uri.fsPath);
      assert.equal(target.getText().slice(target.offsetAt(results[0].range.start), target.offsetAt(results[0].range.end)), 'ledger');
    }
  }
});

test('explicit schema command follows native alias types without changing ordinary declarations', async () => {
  const state = harness();
  state.put('ledger.serializer', 'serializer version 1; class ledger {}');
  state.put('build/ledger.hpp', banner + 'class ledger {};');
  state.put('main.cpp', 'using alias = ledger; alias value;');
  const document = state.document('main.cpp');
  const header = state.document('build/ledger.hpp');
  const aliasPosition = document.positionAt(document.getText().indexOf('alias'));
  const typePosition = header.positionAt(header.getText().indexOf('ledger'));
  state.providers.cpp = () => [{ uri: document.uri, range: { start: aliasPosition, end: aliasPosition } }];
  state.providers.type = () => [{ uri: header.uri, range: { start: typePosition, end: typePosition } }];
  assert.deepEqual(await state.request('main.cpp', 'alias value', false), []);
  assert.ok(!state.calls.includes('vscode.executeTypeDefinitionProvider'));
  const position = document.positionAt(document.getText().indexOf('alias value'));
  state.vscode.window.activeTextEditor = { document, selection: { start: position, active: position } };
  await state.commands.get('serializer.goToSchemaDeclaration')();
  assert.deepEqual(state.calls.slice(-2), ['vscode.executeTypeDefinitionProvider', 'open:ledger.serializer']);
  state.providers.type = () => [];
  await state.commands.get('serializer.goToSchemaDeclaration')();
  assert.equal(state.calls.at(-1), 'vscode.executeTypeDefinitionProvider', 'missing native type is a silent miss');
});

test('missing generated output in every language remains missing after all navigation requests', async () => {
  const state = harness({ trusted: false });
  state.put('ledger.serializer', 'serializer version 1; class ledger {}');
  const originalFiles = () => [...state.files.entries()];
  for (const language of ['cpp', 'c', 'java', 'javascript', 'typescript', 'go', 'csharp', 'rust', 'python', 'swift', 'kotlin']) {
    state.put(`consumer.${language}`, 'ledger value');
    const document = state.document(`consumer.${language}`, language);
    state.providers.cpp = () => [{ uri: state.vscode.Uri.file(path.join(root, 'missing', `ledger.${language}`)),
      range: { start: { line: 0, character: 0 }, end: { line: 0, character: 6 } } }];
    state.providers.type = state.providers.cpp;
    const before = originalFiles();
    assert.deepEqual(await state.providers.declaration.provideDeclaration(document, { line: 0, character: 0 }, state.cancellation), []);
    state.vscode.window.activeTextEditor = { document, selection: { start: { line: 0, character: 0 } } };
    await state.commands.get('serializer.goToSchemaDeclaration')();
    const schema = state.document('ledger.serializer');
    await state.commands.get('serializer.openGeneratedHeader')(schema.uri);
    await state.commands.get('serializer.goToImplementation')(schema.uri);
    assert.deepEqual(originalFiles(), before, language);
    assert.ok(!state.calls.some(call => call.startsWith('open:')));
  }
  assert.ok(state.calls.every(call => ['vscode.executeDefinitionProvider', 'vscode.executeTypeDefinitionProvider'].includes(call)),
    'navigation does not activate CMake, invoke a build or offer a generation prompt');
});

/** Model the read-only Git index tab independently of the working-tree text. */
function gitDocument(state, name, text) {
  const original = state.document(name);
  const uri = { scheme: 'git', fsPath: original.uri.fsPath + '.git',
    query: JSON.stringify({ path: original.uri.fsPath, ref: '~' }),
    toString: () => `git://${original.uri.fsPath}?index` };
  return { ...original, uri, getText: () => text,
    offsetAt: position => text.split('\n').slice(0, position.line).reduce((sum, line) => sum + line.length + 1, 0) + position.character,
    positionAt: offset => { const before = text.slice(0, offset).split('\n'); return { line: before.length - 1, character: before.at(-1).length }; } };
}

test('Git index providers resolve the displayed include at every cursor boundary', async () => {
  const state = harness({ trusted: false });
  const name = 'example/swift/generics/model.serializer';
  state.put(name, 'serializer version 1; include wrong;');
  state.put('example/generics/model.serializer', 'serializer version 1; class included {}');
  const text = 'serializer version 1;\n// staged content differs\ninclude ../../generics/model;\n';
  const doc = gitDocument(state, name, text);
  // A dirty working buffer must not replace the selected Git snapshot.
  state.vscode.workspace.textDocuments.push(state.document(name));
  const start = text.indexOf('../../generics/model');
  for (const [selector, provider, method] of [
    ['selector', 'declaration', 'provideDeclaration'],
    ['definitionSelector', 'definition', 'provideDefinition'],
    ['typeSelector', 'typeDefinition', 'provideTypeDefinition']
  ]) {
    assert.ok(state.providers[selector].some(item => item.language === 'serializer' && item.scheme === 'git'));
    for (let offset = start; offset <= start + '../../generics/model'.length; ++offset) {
      const targets = await state.providers[provider][method](doc, doc.positionAt(offset), state.cancellation);
      assert.equal(targets.length, 1);
      assert.equal(targets[0].uri.fsPath, path.join(root, 'example/generics/model.serializer'));
      assert.equal(targets[0].uri.scheme, 'file');
    }
  }
  assert.deepEqual(state.calls, []);
});

test('Git generic parameters retain snapshot locations and qualified arguments follow current includes', async () => {
  const state = harness({ trusted: false });
  state.put('model.serializer', 'serializer version 1; class different {}');
  state.put('middle.serializer', 'include types;');
  state.put('types.serializer', 'namespace data { class person {} }');
  const text = 'serializer version 1;\ninclude middle;\nclass box<T> { public T value; }\nclass root { public box<data::person> value; }';
  const doc = gitDocument(state, 'model.serializer', text);
  const parameter = text.indexOf('T value');
  const targets = await state.providers.typeDefinition.provideTypeDefinition(doc, doc.positionAt(parameter), state.cancellation);
  assert.equal(targets.length, 1);
  assert.equal(targets[0].uri, doc.uri);
  assert.deepEqual(targets[0].range.start, doc.positionAt(text.indexOf('T>')));
  const argument = text.indexOf('data::person');
  const included = await state.providers.declaration.provideDeclaration(doc, doc.positionAt(argument), state.cancellation);
  assert.equal(included[0].uri.fsPath, path.join(root, 'types.serializer'));
  // Requests against the ordinary file still use its own content.
  assert.equal((await state.request('model.serializer', 'different', false)).length, 1);
});
