const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vscode = require('vscode');
const manifest = require('../package.json');

/** Exercise standard navigation commands in VS Code using only already available artifacts. */
async function runSuite() {
  const workspace = vscode.Uri.file(process.env.SERIALIZER_TEST_WORKSPACE).fsPath;
  const banner = '// Generated by Serializer. Do not edit this file manually.\n';
  const input = path.join(workspace, 'request.serializer');
  const common = path.join(workspace, 'types/account.serializer');
  const header = path.join(workspace, 'build/request.hpp');
  const cpp = path.join(workspace, 'main.cpp');
  fs.mkdirSync(path.dirname(common), { recursive: true });
  fs.mkdirSync(path.dirname(header), { recursive: true });
  fs.writeFileSync(input, 'serializer version 1;\ninclude types/account.serializer;\nclass request { public data::account owner; }\n');
  fs.writeFileSync(common, 'serializer version 1;\nnamespace data { class account {} }\n');
  fs.writeFileSync(header, banner + 'namespace data { class account {}; }\nclass request {};\n');
  fs.writeFileSync(cpp, '#include "build/request.hpp"\ndata::account value{};\n');
  const escape = value => value.replaceAll('\\', '/').replaceAll('$', () => '$$').replace(/[ #:]/g, '\\$&');
  fs.writeFileSync(`${header}.d`, `${escape(header)}: ${escape(input)} ${escape(common)}\n`);
  const extension = vscode.extensions.getExtension(`${manifest.publisher}.${manifest.name}`);
  await extension.activate();
  assert.equal(vscode.extensions.getExtension('ms-vscode.cmake-tools'), undefined);
  const schema = await vscode.workspace.openTextDocument(input);
  await vscode.window.showTextDocument(schema);
  assert.equal(schema.languageId, 'serializer');

  /** Invoke built-in provider commands and normalize Location/LocationLink results. */
  async function navigate(document, text, definition) {
    const position = document.positionAt(document.getText().indexOf(text));
    const targets = await vscode.commands.executeCommand(definition
      ? 'vscode.executeDefinitionProvider' : 'vscode.executeDeclarationProvider', document.uri, position);
    return targets.map(target => ({ uri: target.uri ?? target.targetUri,
      range: target.range ?? target.targetSelectionRange ?? target.targetRange }));
  }
  for (const word of ['types/account.serializer', 'data::account']) {
    const declarations = await navigate(schema, word, false);
    assert.equal(declarations.length, 1, `schema declaration: ${word}`);
    assert.equal(declarations[0].uri.fsPath, common);
    const definitions = await navigate(schema, word, true);
    if (!definitions.length) {
      console.log('Navigation inventory:', (await vscode.workspace.findFiles('**/*.{serializer,hpp,hpp.d}',
        '**/{.git,node_modules,.venv}/**')).map(uri => uri.fsPath));
    }
    assert.equal(definitions.length, 1, `schema definition: ${word}`);
    assert.equal(definitions[0].uri.fsPath, header);
  }

  // Use the reported schema to exercise all enum type occurrences before and after generation.
  const autosar = path.join(workspace, 'styles/autosar/account.serializer');
  const autosarHeader = path.join(workspace, 'build/autosar_account.hpp');
  fs.mkdirSync(path.dirname(autosar), { recursive: true });
  fs.copyFileSync(path.resolve(__dirname, '../../../example/coding_styles/autosar/account.serializer'), autosar);
  const autosarDocument = await vscode.workspace.openTextDocument(autosar);
  for (const word of ['AccountState {', 'AccountState currentState', 'AccountState::WaitingForReview']) {
    const definitions = await navigate(autosarDocument, word, true);
    assert.equal(definitions.length, 1, `ungenerated enum definition: ${word}`);
    assert.equal(definitions[0].uri.fsPath, autosar);
    assert.equal(autosarDocument.getText(definitions[0].range), 'AccountState');
    assert.equal(definitions[0].range.start.line, 3, 'enum declaration, not its field reference');
    assert.equal((await navigate(autosarDocument, word, false))[0].uri.fsPath, autosar);
  }
  fs.writeFileSync(autosarHeader, banner + 'namespace style_demo { enum class account_state { waiting_for_review, active }; }\n');
  fs.writeFileSync(`${autosarHeader}.d`, `${escape(autosarHeader)}: ${escape(autosar)}\n`);
  const generatedAutosar = await vscode.workspace.openTextDocument(autosarHeader);
  const enumDefinitions = await navigate(autosarDocument, 'AccountState::WaitingForReview', true);
  assert.equal(enumDefinitions.length, 1);
  assert.equal(enumDefinitions[0].uri.fsPath, autosarHeader);
  assert.equal(generatedAutosar.getText(enumDefinitions[0].range), 'account_state');

  await vscode.commands.executeCommand('serializer.openGeneratedHeader', vscode.Uri.file(common));
  assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, header);
  const cppDocument = await vscode.workspace.openTextDocument(cpp);
  assert.equal((await navigate(cppDocument, 'build/request.hpp', false))[0].uri.fsPath, input);
  assert.equal((await navigate(cppDocument, 'build/request.hpp', true))[0].uri.fsPath, header);

  // Model the independent C++ provider without requiring a compiler or changing its behavior.
  const generated = await vscode.workspace.openTextDocument(header);
  const accountOffset = generated.getText().indexOf('account');
  const typeLocation = new vscode.Location(generated.uri, new vscode.Range(
    generated.positionAt(accountOffset), generated.positionAt(accountOffset + 'account'.length)));
  const cppExtension = vscode.extensions.getExtension('ms-vscode.cpptools');
  if (cppExtension) {
    await cppExtension.activate();
    await vscode.window.showTextDocument(cppDocument);
    for (let attempt = 0; attempt < 40; ++attempt) {
      if ((await navigate(cppDocument, 'account value', true)).some(target => target.uri.fsPath === header)) { break; }
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }
  const native = cppExtension ? { dispose() {} } : vscode.languages.registerDefinitionProvider({ language: 'cpp', scheme: 'file' }, {
    provideDefinition(document, position) {
      return document.uri.fsPath === cpp && position.line === 1 ? [typeLocation] : [];
    }
  });
  try {
    const declarations = await navigate(cppDocument, 'account value', false);
    assert.ok(declarations.some(target => target.uri.fsPath === common), 'C++ class resolves to its originating schema');
    assert.equal((await navigate(cppDocument, 'account value', true))[0].uri.fsPath, header);
    const editor = await vscode.window.showTextDocument(cppDocument);
    const position = cppDocument.positionAt(cppDocument.getText().indexOf('account value'));
    editor.selection = new vscode.Selection(position, position);
    await vscode.commands.executeCommand('serializer.goToSchemaDeclaration');
    assert.equal(vscode.window.activeTextEditor.document.uri.fsPath, common);
  } finally { native.dispose(); }

  // Unsaved schema edits participate in declaration navigation and are never saved by it.
  const change = new vscode.WorkspaceEdit();
  change.insert(schema.uri, schema.positionAt(schema.getText().length), '\nclass unsaved {}\n');
  await vscode.workspace.applyEdit(change);
  assert.equal((await navigate(schema, 'unsaved', false))[0].uri.fsPath, input);
  assert.equal((await navigate(schema, 'unsaved', true))[0].uri.fsPath, input);
  assert.equal(schema.isDirty, true);
  assert.ok(!fs.readFileSync(input, 'utf8').includes('unsaved'));
  const missing = path.join(workspace, 'missing.serializer');
  fs.writeFileSync(missing, 'serializer version 1; class missing {}');
  const missingDocument = await vscode.workspace.openTextDocument(missing);
  assert.equal((await navigate(missingDocument, 'missing', true))[0].uri.fsPath, missing);
  await vscode.commands.executeCommand('serializer.openGeneratedHeader', missingDocument.uri);
  assert.equal(fs.existsSync(path.join(workspace, 'build/missing.hpp')), false);
  console.log('Serializer navigation host passed: schema and C++ includes/types, AUTOSAR enum defaults, schema fallback, merged output, ignored build directory, unsaved buffers, missing output, and no CMake/build dependency.');
  if (cppExtension) { console.log(`Verified native Microsoft C/C++ ${cppExtension.packageJSON.version} navigation.`); }
}

/** Fail promptly if a provider deadlocks or unexpectedly displays an interactive prompt. */
exports.run = async function run() {
  let timer;
  try {
    await Promise.race([runSuite(), new Promise((_, reject) => {
      timer = setTimeout(() => reject(new Error('Navigation integration test timed out')), 60_000);
    })]);
  } finally { clearTimeout(timer); }
};
