<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <OutputType>Exe</OutputType>
    <AssemblyName>SerializerNavigationTest</AssemblyName>
    <OutputPath>..\..\..\out\extension-tests\visual-studio\</OutputPath>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <LangVersion>latest</LangVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Jint" Version="4.16.2" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Web.Extensions" />
    <Compile Include="..\navigation_runner.cs" Link="navigation_runner.cs" />
    <Compile Include="navigation_test.cs" />
    <EmbeddedResource Include="..\obj\navigation.js" LogicalName="Rohit.Serializer.navigation.js" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
