import java.nio.file.Files;
import java.nio.file.Path;

/** Exercise byte-key identity without requiring cross-language map iteration order. */
public final class Main {
  private static final int[] KEYS = {255, 127, 0, 128};
  private static final int VALUE_BASE = 1000;
  private static final String[] PROTOCOL_NAMES = {"json", "positional", "integer", "string"};

  /** Build the independent fixture using Java's generated byte-key map. */
  private static Schema.CharMap fixture(boolean asciiOnly) {
    var value = new Schema.CharMap();
    for (int key : KEYS) {
      if (!asciiOnly || key <= 127) {
        value.entries.put((byte) key, VALUE_BASE + key);
      }
    }
    return value;
  }

  /** Require complete values for every producer and retain the JSON ASCII restriction. */
  public static void main(String[] args) throws Exception {
    if (args.length != 2 || !(args[1].equals("emit") || args[1].equals("verify"))) {
      throw new IllegalArgumentException("Expected fixture directory and emit/verify");
    }
    Path directory = Path.of(args[0]);
    boolean rejected = false;
    try {
      fixture(false).encode(Schema.Protocol.JSON);
    } catch (IllegalArgumentException expected) {
      rejected = true;
    }
    if (!rejected) {
      throw new AssertionError("JSON accepted a high-bit character key");
    }
    for (Schema.Protocol protocol : Schema.Protocol.values()) {
      var expected = fixture(protocol == Schema.Protocol.JSON);
      String suffix = "_" + PROTOCOL_NAMES[protocol.ordinal()] + ".bin";
      if (args[1].equals("emit")) {
        Files.write(directory.resolve("java" + suffix), expected.encode(protocol));
      } else {
        for (String producer : Files.readAllLines(directory.resolve("producers.txt"))) {
          var actual = Schema.CharMap.decode(Files.readAllBytes(directory.resolve(producer + suffix)), protocol);
          if (!actual.entries.equals(expected.entries)) {
            throw new AssertionError("Character-map data changed: " + producer + suffix);
          }
        }
      }
    }
  }
}
