import * as path from 'node:path';
import { codeOnly, generatedNames, indexSource, SourceIndex, TypeSymbol } from './navigation_model';

export const navigationLanguages = ['serializer', 'cpp', 'c', 'java', 'javascript', 'javascriptreact',
  'typescript', 'typescriptreact', 'go', 'csharp', 'rust', 'python', 'swift', 'kotlin'];
export const outputPattern = '**/*.{hpp,h,hxx,hh,java,js,mjs,cjs,ts,mts,cts,go,cs,rs,py,swift,kt,d}';

/** Recognize emitted file types, including TypeScript companion declarations. */
export function outputLanguage(file: string): string | undefined {
  const extension = path.extname(file).toLowerCase();
  return ({ '.hpp': 'cpp', '.h': 'cpp', '.hh': 'cpp', '.hxx': 'cpp', '.java': 'java',
    '.js': 'javascript', '.mjs': 'javascript', '.cjs': 'javascript', '.ts': 'typescript',
    '.mts': 'typescript', '.cts': 'typescript', '.go': 'go', '.cs': 'csharp', '.rs': 'rust',
    '.py': 'python', '.swift': 'swift', '.kt': 'kotlin' } as Record<string, string>)[extension];
}

/** Distinguish native C's emitted header from C++ even when the editor associates .h with C++. */
export function generatedLanguage(file: string, text: string): string | undefined {
  return path.extname(file).toLowerCase() === '.h' && text.includes('#define SRL_NATIVE_RUNTIME_INCLUDED')
    ? 'c' : outputLanguage(file);
}

/** Allow legacy basename lookup only for files explicitly marked as Serializer output. */
export function generatedBanner(text: string): boolean {
  return /^\s*\/\/ Generated by (?:Serializer\.|the C\+\+ Serializer compiler\.)/.test(text);
}

/** Mask language-specific comments and literals without shifting source offsets. */
function generatedCode(text: string, language: string): string {
  const hide = (match: string): string => match.replace(/[^\r\n]/g, ' ');
  if (language === 'python') {
    return text.replace(/#[^\r\n]*|"""[\s\S]*?(?:"""|$)|'''[\s\S]*?(?:'''|$)|"(?:\\[\s\S]|[^"\\])*"|'(?:\\[\s\S]|[^'\\])*'/g, hide);
  }
  if (language === 'rust') {
    // Lifetimes such as 'a are not character literals and must not swallow declarations.
    return text.replace(/\/\*[\s\S]*?(?:\*\/|$)|\/\/[^\r\n]*|r(#+)?"[\s\S]*?"\1|"(?:\\[\s\S]|[^"\\])*"|'(?:\\[^\r\n]|[^'\\\r\n])'/g, hide);
  }
  return codeOnly(text.replace(/`(?:\\[\s\S]|[^`\\])*`/g, hide));
}

/** Index the actual declaration forms emitted by each generator, excluding runtime references. */
export function indexGeneratedSource(text: string, file: string): SourceIndex {
  const language = generatedLanguage(file, text);
  if (language === 'cpp' || language === 'java' || language === 'csharp' || language === 'c') {
    const result = indexSource(text, false, language === 'java');
    if (language === 'csharp') {
      // Schema namespaces are flattened; the configurable C# namespace is only a wrapper.
      for (const symbol of result.symbols) { symbol.qualified = symbol.name; }
    }
    if (language === 'c') {
      // C services can resolve either a struct tag or its typedef name.
      for (const match of codeOnly(text).matchAll(/\btypedef\s+(struct|enum)\s+([A-Za-z_]\w*)\s+([A-Za-z_]\w*)\s*;/g)) {
        const tag = match.index! + match[0].indexOf(match[2]);
        const start = match.index! + match[0].lastIndexOf(match[3]);
        result.symbols.push({ name: match[2], qualified: match[2], kind: match[1] === 'enum' ? 'enum' : 'class',
          start: tag, end: tag + match[2].length, body: tag, declaration: match.index!, definition: false });
        result.symbols.push({ name: match[3], qualified: match[3], kind: match[1] === 'enum' ? 'enum' : 'class',
          start, end: start + match[3].length, body: start, declaration: start, definition: false });
      }
      const code = codeOnly(text);
      for (const symbol of [...result.symbols].filter(item => item.definition && item.kind === 'enum')) {
        let end = symbol.body;
        let depth = 0;
        do {
          if (code[end] === '{') { ++depth; }
          if (code[end] === '}') { --depth; }
          ++end;
        } while (end < code.length && depth > 0);
        const alias = /^\s*([A-Za-z_]\w*)\s*;/.exec(code.slice(end));
        if (alias) {
          const start = end + alias[0].indexOf(alias[1]);
          result.symbols.push({ ...symbol, name: alias[1], qualified: alias[1], start,
            end: start + alias[1].length, declaration: start, definition: false });
        }
      }
    }
    return result;
  }
  const code = generatedCode(text, language ?? '');
  const patterns: Record<string, RegExp> = {
    python: /^class\s+([A-Za-z_]\w*)\s*(\([^\r\n]*\))?\s*:/gm,
    go: /^type\s+([A-Za-z_]\w*)\s+(struct\s*\{|int32\b)/gm,
    rust: /^pub\s+(struct|enum)\s+([A-Za-z_]\w*)\b/gm,
    swift: /^public\s+(struct|enum|class)\s+([A-Za-z_]\w*)\b/gm,
    kotlin: /^(enum\s+class|class)\s+([A-Za-z_]\w*)\b/gm,
    javascript: /^export\s+(class|const)\s+([A-Za-z_]\w*)\b/gm,
    typescript: /^export\s+(?:declare\s+)?(class|const)\s+([A-Za-z_]\w*)\b/gm
  };
  const symbols: TypeSymbol[] = [];
  for (const match of code.matchAll(patterns[language ?? ''] ?? /$^/g)) {
    const name = language === 'python' || language === 'go' ? match[1] : match[2];
    const enumType = language === 'python' ? match[2]?.includes('_IntEnum')
      : language === 'go' ? match[2] === 'int32' : /enum|const/.test(match[1]);
    const start = match.index! + match[0].indexOf(name);
    symbols.push({ name, qualified: name, kind: enumType ? 'enum' : 'class', start,
      end: start + name.length, declaration: match.index!, body: start, definition: true });
  }
  if (language === 'typescript') {
    // Type-position lookups often return the companion alias instead of the enum value object.
    for (const match of code.matchAll(/^export\s+type\s+([A-Za-z_]\w*)\s*=\s*typeof\s+\1\s*\[/gm)) {
      const start = match.index! + match[0].indexOf(match[1]);
      symbols.push({ name: match[1], qualified: match[1], kind: 'enum', start, end: start + match[1].length,
        declaration: match.index!, body: start, definition: false });
    }
  }
  return { symbols, includes: [], references: [] };
}

/** Reproduce namespace containers/flattening and preserve/profile type spellings per language. */
export function outputNames(qualified: string, file: string, text: string): string[] {
  const language = generatedLanguage(file, text);
  if (language === 'cpp') { return generatedNames(qualified); }
  const parts = qualified.split('::');
  // Java normalizes acronym words; the portable/native generators preserve internal capitals.
  const pascal = parts.map(part => part.split('_')
    .map(word => word ? word[0].toUpperCase() + word.slice(1) : '').join(''));
  if (language === 'java') {
    const outer = path.basename(file, path.extname(file));
    const normalized = parts.map(part => part.replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/([A-Z0-9])([A-Z][a-z])/g, '$1_$2').split('_').filter(Boolean)
      .map(word => word[0].toUpperCase() + word.slice(1).toLowerCase()).join(''));
    return [...new Set([parts, normalized].map(names => [outer, ...names].join('::')))];
  }
  if (language === 'c') {
    return [pascal.join('').replace(/([a-z])([A-Z])/g, '$1_$2')
      .replace(/([A-Z0-9])([A-Z][a-z])/g, '$1_$2').toLowerCase()];
  }
  return ['rust', 'python', 'swift', 'kotlin'].includes(language ?? '') ? [pascal.join('')]
    : [...new Set([parts.join(''), pascal.join('')])];
}
