import * as path from 'node:path';
import { fileKey, includeCandidates } from './model';
import { cppIncludeAt, dependencySchemas, generatedNames, indexSource, resolveType,
  SourceIndex, Span, TypeSymbol } from './navigation_model';

export interface NavigationTarget extends Span { file: string }
export interface NavigationFiles { schemas: string[]; headers: string[] }
export interface NavigationHost {
  read(file: string): Promise<string | undefined>;
  files(): Promise<NavigationFiles>;
  includeDirectories: string[][];
  cancelled(): boolean;
}
interface Source { file: string; text: string; index: SourceIndex }
interface Declaration extends TypeSymbol { file: string }
const maximumIncludeDepth = 128;
const maximumSchemaFiles = 4096;
const generatedBanner = '// Generated by Serializer. Do not edit this file manually.';

/** Resolve read-only navigation from existing source, headers and optional dependency files. */
export class Navigator {
  private readonly sources = new Map<string, Promise<Source | undefined>>();
  private readonly graphs = new Map<string, Promise<Source[]>>();
  private readonly owners = new Map<string, Promise<string[]>>();
  private inventory?: Promise<NavigationFiles>;

  /** Keep request state isolated so cancellation or file changes cannot publish stale locations. */
  constructor(private readonly host: NavigationHost) {}

  /** Share one workspace discovery operation within this request. */
  private files(): Promise<NavigationFiles> {
    return this.inventory ??= this.host.files();
  }

  /** Read and index each file once per request; missing files are ordinary navigation misses. */
  private source(file: string): Promise<Source | undefined> {
    const key = fileKey(file);
    let source = this.sources.get(key);
    if (!source) {
      source = this.host.cancelled() ? Promise.resolve(undefined) : this.host.read(file).then(text =>
        text === undefined ? undefined : { file, text, index: indexSource(text, file.endsWith('.serializer')) });
      this.sources.set(key, source);
    }
    return source;
  }

  /** Traverse schema includes once, preserving source ownership through diamonds and cycles. */
  private graph(entry: string): Promise<Source[]> {
    const key = fileKey(entry);
    let graph = this.graphs.get(key);
    if (!graph) {
      graph = this.loadGraph(entry);
      this.graphs.set(key, graph);
    }
    return graph;
  }

  /** Bound malformed/cyclic include trees without dropping available declarations. */
  private async loadGraph(entry: string): Promise<Source[]> {
    const result: Source[] = [];
    const seen = new Set<string>();
    const pending = [{ file: entry, depth: 0 }];
    while (pending.length && seen.size < maximumSchemaFiles && !this.host.cancelled()) {
      const item = pending.pop()!;
      const key = fileKey(item.file);
      if (seen.has(key) || item.depth >= maximumIncludeDepth) { continue; }
      seen.add(key);
      const source = await this.source(item.file);
      if (!source) { continue; }
      result.push(source);
      for (const include of source.index.includes) {
        pending.push({ file: path.resolve(path.dirname(item.file), include.name), depth: item.depth + 1 });
      }
    }
    return result;
  }

  /** Identify entry schemas from authoritative depfiles, or all matching legacy basenames. */
  private headerEntries(header: string): Promise<string[]> {
    const key = fileKey(header);
    let entries = this.owners.get(key);
    if (!entries) {
      entries = this.findHeaderEntries(header);
      this.owners.set(key, entries);
    }
    return entries;
  }

  /** Require the Serializer banner so ordinary C++ headers never acquire schema ownership. */
  private async findHeaderEntries(header: string): Promise<string[]> {
    const text = await this.host.read(header);
    if (!text?.trimStart().startsWith(generatedBanner)) { return []; }
    const depfile = await this.host.read(`${header}.d`);
    if (depfile !== undefined) {
      // An invalid/mismatched depfile must not fall back to an unrelated same-name schema.
      return dependencySchemas(depfile, header).slice(0, 1);
    }
    const stem = fileKey(path.basename(header, path.extname(header)));
    return (await this.files()).schemas.filter(file =>
      fileKey(path.basename(file, '.serializer')) === stem);
  }

  /** Keep duplicate include paths and provider locations from appearing more than once. */
  private unique(targets: NavigationTarget[]): NavigationTarget[] {
    if (this.host.cancelled()) { return []; }
    return [...new Map(targets.map(target =>
      [`${fileKey(target.file)}:${target.start}:${target.end}`, target])).values()];
  }

  /** Return the exact declaration selected in a schema, including transitive included types. */
  private async declarations(file: string, offset: number): Promise<Declaration[]> {
    const source = await this.source(file);
    const reference = source?.index.references.find(item => offset >= item.start && offset < item.end);
    if (!reference) { return []; }
    const declarations = (await this.graph(file)).flatMap(item =>
      item.index.symbols.map(symbol => ({ ...symbol, file: item.file })));
    return resolveType(reference, declarations) as Declaration[];
  }

  /** Locate existing output headers containing this schema; favor its current entry compilation. */
  private async outputs(schema: string, context: string): Promise<string[]> {
    const preferred: string[] = [];
    const available: string[] = [];
    for (const header of (await this.files()).headers) {
      if (this.host.cancelled()) { return []; }
      for (const entry of await this.headerEntries(header)) {
        const graph = await this.graph(entry);
        if (!graph.some(source => fileKey(source.file) === fileKey(schema))) { continue; }
        available.push(header);
        if (fileKey(entry) === fileKey(context)) { preferred.push(header); }
      }
    }
    return [...new Set(preferred.length ? preferred : available)];
  }

  /** Prefer generated type definitions, falling back to their schema without generating output. */
  async schema(file: string, offset: number, definition: boolean): Promise<NavigationTarget[]> {
    const source = await this.source(file);
    const include = source?.index.includes.find(item => offset >= item.start && offset < item.end);
    if (include) {
      const included = path.resolve(path.dirname(file), include.name);
      if (!await this.source(included)) { return []; }
      if (!definition) { return [{ file: included, start: 0, end: 0 }]; }
      return this.unique((await this.outputs(included, file)).map(header => ({ file: header, start: 0, end: 0 })));
    }
    const declarations = await this.declarations(file, offset);
    if (!definition) { return this.unique(declarations); }
    const targets: NavigationTarget[] = [];
    for (const declaration of declarations) {
      const names = generatedNames(declaration.qualified);
      for (const header of await this.outputs(declaration.file, file)) {
        const generated = await this.source(header);
        const matches = (generated?.index.symbols ?? []).filter(symbol =>
          symbol.definition && symbol.kind === declaration.kind && names.includes(symbol.qualified));
        // Preserve distinct identifiers in naming=preserve outputs that normalize alike.
        const exact = matches.filter(symbol => symbol.qualified === declaration.qualified);
        for (const symbol of exact.length ? exact : matches) {
          targets.push({ file: header, start: symbol.start, end: symbol.end });
        }
      }
    }
    return this.unique(targets.length ? targets : declarations);
  }

  /** Open only existing generated outputs for a whole schema, including included-only schemas. */
  async headers(file: string): Promise<NavigationTarget[]> {
    return this.unique((await this.outputs(file, file)).map(header => ({ file: header, start: 0, end: 0 })));
  }

  /** Resolve literal C++ includes in compiler search order, then use available workspace outputs. */
  async cppInclude(file: string, offset: number, definition: boolean): Promise<NavigationTarget[]> {
    const source = await this.source(file);
    const include = source && cppIncludeAt(source.text, offset);
    if (!include) { return []; }
    const headers: string[] = [];
    let shadowed = false;
    const groups = this.host.includeDirectories;
    for (const directories of groups.length ? groups : [[]]) {
      for (const candidate of includeCandidates(file, include, directories)) {
        const text = await this.host.read(candidate);
        if (text === undefined) { continue; }
        // An ordinary header earlier on the search path shadows Serializer outputs too.
        if (text.trimStart().startsWith(generatedBanner)) { headers.push(candidate); }
        else { shadowed = true; }
        if (!groups.length) { return this.includeTargets(headers, definition); }
        break;
      }
    }
    if (!groups.length && !headers.length) {
      const suffix = fileKey(path.normalize(include.name));
      for (const header of (await this.files()).headers) {
        if (fileKey(header).endsWith(path.sep + suffix) &&
          (await this.host.read(header))?.trimStart().startsWith(generatedBanner)) {
          headers.push(header);
        }
      }
    }
    if (!definition && !headers.length && !shadowed && /\.(hpp|h|hxx|hh)$/.test(include.name)) {
      // Declaration navigation remains useful before the very first generation.
      const stem = fileKey(path.basename(include.name, path.extname(include.name)));
      return this.unique((await this.files()).schemas.filter(schema =>
        fileKey(path.basename(schema, '.serializer')) === stem)
        .map(schema => ({ file: schema, start: 0, end: 0 })));
    }
    return this.includeTargets(headers, definition);
  }

  /** Map include targets to entry schemas, excluding deleted destinations. */
  private async includeTargets(headers: string[], definition: boolean): Promise<NavigationTarget[]> {
    const targets: NavigationTarget[] = [];
    for (const header of headers) {
      for (const file of definition ? [header] : await this.headerEntries(header)) {
        if (await this.host.read(file) !== undefined) { targets.push({ file, start: 0, end: 0 }); }
      }
    }
    return this.unique(targets);
  }

  /** Translate a C++ language service's resolved class location back to its schema declaration. */
  async cppDeclaration(header: string, offset: number): Promise<NavigationTarget[]> {
    const entries = await this.headerEntries(header);
    if (!entries.length) { return []; }
    const source = await this.source(header);
    const symbol = source?.index.symbols.find(item => offset >= item.declaration && offset < item.end);
    if (!symbol) { return []; }
    const targets: NavigationTarget[] = [];
    for (const entry of entries) {
      const matches: Declaration[] = [];
      for (const schema of await this.graph(entry)) {
        for (const declaration of schema.index.symbols) {
          if (declaration.kind === symbol.kind && generatedNames(declaration.qualified).includes(symbol.qualified)) {
            matches.push({ ...declaration, file: schema.file });
          }
        }
      }
      const exact = matches.filter(declaration => declaration.qualified === symbol.qualified);
      targets.push(...(exact.length ? exact : matches));
    }
    return this.unique(targets);
  }
}
