#include "native_schema.hpp"

#include <map>
#include <string>

namespace rohit::serializer::writer::native {
namespace {
constexpr std::string_view runtime =
#include "rust_runtime.inc"
    ;
constexpr std::string_view keywords =
    " as async await break const continue crate dyn else enum extern false fn for if impl in let "
    "loop match mod move mut pub ref return self Self static struct super trait true type unsafe "
    "use where while abstract become box do final macro override priv typeof unsized virtual yield "
    "try gen BTreeMap ";
// Emit Rust source with statically typed fields and fallible exact decoding.
class rust_emitter {
  const schema& model;
  std::string output{
      "// Generated by the C++ Serializer compiler.\n#![allow(dead_code, unused_imports)]\n"};
  std::size_t indent{};
  // Append a Rust source line.
  void line(const std::string& text = {}) {
    output.append(indent * 4, ' ');
    output += text + '\n';
  }
  // Begin a lexical scope.
  void open(const std::string& text) {
    line(text + " {");
    ++indent;
  }
  // End a lexical scope.
  void close() {
    --indent;
    line("}");
  }
  // Validate snake_case field names against Rust keywords.
  std::string field(std::string_view name) const {
    auto result = snake(name);
    validate_identifier(result, keywords);
    return result;
  }
  // Map schema scalars to their exact native Rust representation.
  std::string type(const type_name& value) const {
    if (value.type != object_type::primitive) {
      return model.names.at(value.resolved_node);
    }
    if (value.name == "string") {
      return "String";
    }
    if (value.name == "char") {
      return "u8";
    }
    if (value.name == "float") {
      return "f32";
    }
    if (value.name == "double") {
      return "f64";
    }
    if (value.name == "bool") {
      return "bool";
    }
    return (value.name.starts_with('u') ? "u" : "i") + std::to_string(width(value) * 8);
  }
  // Translate the two portable escapes not spelled the same way in Rust.
  std::string text_literal(std::string value) const {
    for (std::size_t i = 1; i + 1 < value.size(); ++i) {
      if (value[i] != '\\') {
        continue;
      }
      ++i;
      if (value[i] == 'b' || value[i] == 'f') {
        const auto replacement = value[i] == 'b' ? "u{8}" : "u{c}";
        value.replace(i, 1, replacement);
        i += 3;
      }
    }
    return value;
  }
  // Construct independent schema defaults for owned values.
  std::string initial(const type_name& value, std::string literal_value = {}) const {
    if (value.type == object_type::class_type) {
      return type(value) + "::default()";
    }
    if (value.type == object_type::enum_type) {
      const auto& constants = static_cast<const enum_node&>(*value.resolved_node).enum_name_list;
      return type(value) + "::" + pascal(literal_value.empty() ? constants.front() : literal_value);
    }
    if (value.name == "string") {
      return literal_value.empty() ? "String::new()" : text_literal(literal_value) + ".to_owned()";
    }
    if (value.name == "bool") {
      return literal_value.empty() ? "false" : literal_value;
    }
    if (value.name == "float" || value.name == "double") {
      return "(" + (literal_value.empty() ? "0.0" : literal_value) + " as " + type(value) + ")";
    }
    return literal_value.empty() ? "0" : literal_value;
  }
  // Decode one scalar with explicit wire context.
  std::string read(const type_name& value, bool collection) const {
    if (value.type == object_type::class_type) {
      return "{ let mut value = " + type(value) + "::default(); value.srl_read(input)?; value }";
    }
    if (value.type == object_type::enum_type) {
      return type(value) + "::srl_read(input, " + (collection ? "true" : "false") + ")?";
    }
    if (value.name == "string") {
      return "input.text()?";
    }
    if (value.name == "bool") {
      return "input.boolean()?";
    }
    if (value.name == "char") {
      return "input.character()?";
    }
    if (value.name == "float" || value.name == "double") {
      return value.name == "float" ? "input.float32()?" : "input.float64()?";
    }
    return "input.integer(" + std::to_string(width(value)) + ", " +
           (value.name.starts_with('u') ? "true" : "false") + ")? as " + type(value);
  }
  // Write a borrowed scalar without copying owning fields.
  void write(const type_name& value, const std::string& expression, bool collection) {
    if (value.type == object_type::class_type) {
      line(expression + ".srl_write(out)?;");
    } else if (value.type == object_type::enum_type) {
      line(expression + ".srl_write(out, " + (collection ? "true" : "false") + ")?;");
    } else if (value.name == "string") {
      line(
          "out.text(" +
          (expression.starts_with('(') ? expression.substr(1, expression.size() - 2) : expression) +
          ")?;");
    } else if (value.name == "bool") {
      line("out.boolean(*" + expression + ")?;");
    } else if (value.name == "char") {
      line("out.character(*" + expression + ")?;");
    } else if (value.name == "float" || value.name == "double") {
      line("out." + std::string{value.name == "float" ? "float32" : "float64"} + "(*" + expression +
           ")?;");
    } else {
      line("out.integer(*" + expression + " as u64, " + std::to_string(width(value)) + ", " +
           (value.name.starts_with('u') ? "true" : "false") + ")?;");
    }
  }
  // Reference an immutable pre-encoded field table entry.
  void key(std::uint32_t id, const std::string& name, bool first) {
    line("out.field(" + std::to_string(id) + ", " + std::to_string(model.keys.at(name)) + ", " +
         (first ? "true" : "false") + ")?;");
  }
  // Read one field, preserving merge semantics and replacing collections.
  void read_member(const member& value) {
    const auto dst = "self." + field(value.name);
    const auto& t = value.type_name_list.front();
    if (value.modifier == member::modifier_type::none) {
      if (t.type == object_type::class_type) {
        line(dst + ".srl_read(input)?;");
      } else {
        line(dst + " = " + read(t, false) + ";");
      }
      return;
    }
    if (value.modifier == member::modifier_type::variant) {
      line(dst + "_index = match alternative { Some(value) => value, None => input.compact()? };");
      open("match " + dst + "_index");
      for (std::size_t i = 0; i < value.type_name_list.size(); ++i) {
        const auto& alt = value.type_name_list[i];
        open(std::to_string(i) + " =>");
        line(dst + "_" + field(alt.enum_name) + " = " + read(alt, true) + ";");
        close();
      }
      line("_ => return Err(Error(\"Unknown union alternative\")),");
      close();
      return;
    }
    line("let count = input.begin_array()?;");
    line("let mut index = 0;");
    if (value.modifier == member::modifier_type::array) {
      line("let mut values = Vec::new();");
      line("values.try_reserve(input.capacity(count, " + std::to_string(width(t)) +
           ")?).map_err(|_| Error(\"Array allocation\"))?;");
      open("while input.next_element(index, count)?");
      line("values.push(" + read(t, true) + ");");
      line("index += 1;");
      close();
    } else {
      line("let mut values = BTreeMap::new();");
      open("while input.next_element(index, count)?");
      line("let entry_key;");
      line("let entry_value;");
      open("if input.json()");
      line("let mut k = None;");
      line("let mut v = None;");
      line("input.begin_object()?;");
      line("let mut cursor = 0;");
      open("while let Some(key) = input.key(&[], &mut cursor)?");
      open("match key");
      line("SrlKey::Name(name) if name == \"key\" => k = Some(" + read(map_key(value), true) +
           "),");
      line("SrlKey::Name(name) if name == \"value\" => v = Some(" + read(t, true) + "),");
      line("_ => return Err(Error(\"Unknown map entry field\")),");
      close();
      close();
      line("input.end_object();");
      line("entry_key = k.ok_or(Error(\"Incomplete map entry\"))?;");
      line("entry_value = v.ok_or(Error(\"Incomplete map entry\"))?;");
      close();
      open("else");
      line("entry_key = " + read(map_key(value), true) + ";");
      line("entry_value = " + read(t, true) + ";");
      close();
      line("values.insert(entry_key, entry_value);");
      line("index += 1;");
      close();
    }
    line(dst + " = values;");
  }
  // Write ordered collections and selected union payloads directly.
  void write_member(const member& value, bool first) {
    const auto src = "self." + field(value.name);
    const auto& t = value.type_name_list.front();
    if (value.modifier == member::modifier_type::variant) {
      open("match " + src + "_index");
      for (std::size_t i = 0; i < value.type_name_list.size(); ++i) {
        const auto& alt = value.type_name_list[i];
        open(std::to_string(i) + " =>");
        key(value.id, value.display_name + ":" + alt.enum_name, first);
        line("if matches!(out.protocol, Protocol::BinaryNone | Protocol::BinaryInteger) { "
             "out.compact(" +
             std::to_string(i) + ")?; }");
        write(alt, "(&" + src + "_" + field(alt.enum_name) + ")", true);
        close();
      }
      line("_ => return Err(Error(\"Unknown union alternative\")),");
      close();
      return;
    }
    key(value.id, value.display_name, first);
    if (value.modifier == member::modifier_type::none) {
      write(t, "(&" + src + ")", false);
      return;
    }
    line("out.begin_array(" + src + ".len())?;");
    open("for (index, " +
         std::string{value.modifier == member::modifier_type::map ? "(key, value)" : "value"} +
         ") in " + src + ".iter().enumerate()");
    line("out.element(index)?;");
    if (value.modifier == member::modifier_type::map) {
      line("if out.json() { out.begin_object()?; out.field(0, 0, true)?; }");
      write(map_key(value), "key", true);
      line("if out.json() { out.field(0, 1, false)?; }");
      write(t, "value", true);
      line("if out.json() { out.end_object()?; }");
    } else {
      write(t, "value", true);
    }
    close();
    line("out.end_array()?;");
  }
  // Define a class's owned fields, defaults, and transactional public decoding.
  void object(const class_node& value) {
    const auto name = model.names.at(&value);
    struct declaration {
      std::string name, type, initial;
      bool public_access;
    };
    std::vector<declaration> fields;
    for (std::size_t i = 0; i < value.parents.size(); ++i) {
      const auto& base = value.parents[i];
      const auto n = model.names.at(base.parent_class);
      fields.push_back({"base" + std::to_string(i), n, n + "::default()",
                        base.access == access_type::public_access});
    }
    for (const auto& f : value.member_list) {
      const auto id = field(f.name);
      const auto& t = f.type_name_list.front();
      const bool visible = f.access == access_type::public_access;
      if (f.modifier == member::modifier_type::variant) {
        fields.push_back({id + "_index", "usize", "0", visible});
        for (const auto& alt : f.type_name_list) {
          fields.push_back({id + "_" + field(alt.enum_name), type(alt), initial(alt), visible});
        }
      } else if (f.modifier == member::modifier_type::array) {
        fields.push_back({id, "Vec<" + type(t) + ">", "Vec::new()", visible});
      } else if (f.modifier == member::modifier_type::map) {
        fields.push_back({id, "BTreeMap<" + type(map_key(f)) + ", " + type(t) + ">",
                          "BTreeMap::new()", visible});
      } else {
        fields.push_back({id, type(t), initial(t, literal(f)), visible});
      }
    }
    line("/// Owning schema value; encoding borrows its fields.");
    line("#[derive(Clone, Debug, PartialEq)]");
    open("pub struct " + name);
    for (const auto& f : fields) {
      line((f.public_access ? "pub " : "") + f.name + ": " + f.type + ",");
    }
    close();
    open("impl Default for " + name);
    line("/// Construct independent schema defaults.");
    open("fn default() -> Self");
    open("Self");
    for (const auto& f : fields) {
      line(f.name + ": " + f.initial + ",");
    }
    close();
    close();
    close();
    open("impl " + name);
    line("/// Encode one complete message into independent owned bytes.");
    open("pub fn encode(&self, protocol: Protocol) -> Result<Vec<u8>, Error>");
    line("let mut out = SrlWriter::new(protocol);");
    line("self.srl_write(&mut out)?;");
    line("Ok(out.bytes)");
    close();
    line("/// Decode a fresh value and require exact message consumption.");
    open("pub fn decode(bytes: &[u8], protocol: Protocol) -> Result<Self, Error>");
    line("Self::decode_with_limits(bytes, protocol, Limits::default())");
    close();
    line("/// Apply explicit resource limits; no partial value escapes on failure.");
    open("pub fn decode_with_limits(bytes: &[u8], protocol: Protocol, limits: Limits) -> "
         "Result<Self, Error>");
    line("let mut input = SrlReader::new(bytes, protocol, limits)?;");
    line("let mut value = Self::default();");
    line("value.srl_read(&mut input)?;");
    line("input.finish()?;");
    line("Ok(value)");
    close();
    line("/// Write fields in schema order without reflection.");
    open("fn srl_write(&self, out: &mut SrlWriter) -> SrlResult<()>");
    line("out.begin_object()?;");
    bool first = true;
    for (std::size_t i = 0; i < value.parents.size(); ++i) {
      const auto& base = value.parents[i];
      key(base.id, base.display_name, first);
      line("self.base" + std::to_string(i) + ".srl_write(out)?;");
      first = false;
    }
    for (const auto& f : value.member_list) {
      write_member(f, first);
      first = false;
    }
    line("out.end_object()");
    close();
    line("/// Merge repeated nested objects while replacing collections.");
    open("fn srl_read(&mut self, input: &mut SrlReader<'_>) -> SrlResult<()>");
    line("input.begin_object()?;");
    line("let mut cursor = 0;");
    std::string ids = "&[";
    for (const auto& base : value.parents) {
      ids += std::to_string(base.id) + ",";
    }
    for (const auto& f : value.member_list) {
      ids += std::to_string(f.id) + ",";
    }
    ids += "]";
    open("while let Some(key) = input.key(" + ids + ", &mut cursor)?");
    line("let (id, alternative): (u32, Option<usize>) = match key {");
    ++indent;
    line("SrlKey::Id(value) => (value, None),");
    open("SrlKey::Name(name) => match name.as_str()");
    for (const auto& base : value.parents) {
      line(quote(base.display_name) + " => (" + std::to_string(base.id) + ", None),");
    }
    for (const auto& f : value.member_list) {
      if (f.modifier == member::modifier_type::variant) {
        for (std::size_t i = 0; i < f.type_name_list.size(); ++i) {
          line(quote(f.display_name + ":" + f.type_name_list[i].enum_name) + " => (" +
               std::to_string(f.id) + ", Some(" + std::to_string(i) + ")),");
        }
      } else {
        line(quote(f.display_name) + " => (" + std::to_string(f.id) + ", None),");
      }
    }
    line("_ => return Err(Error(\"Unknown field\")),");
    close();
    --indent;
    line("};");
    line("let _ = alternative;");
    open("match id");
    for (std::size_t i = 0; i < value.parents.size(); ++i) {
      line(std::to_string(value.parents[i].id) + " => self.base" + std::to_string(i) +
           ".srl_read(input)?,");
    }
    for (const auto& f : value.member_list) {
      open(std::to_string(f.id) + " =>");
      read_member(f);
      close();
    }
    line("_ => return Err(Error(\"Unknown field\")),");
    close();
    close();
    line("input.end_object();");
    line("Ok(())");
    close();
    close();
  }
  // Emit a static byte slice without relying on source encoding or escape ambiguity.
  std::string bytes(const std::string& value) const {
    std::string text = "&[";
    for (const auto ch : value) {
      text += std::to_string(static_cast<unsigned char>(ch)) + ",";
    }
    return text + "]";
  }

public:
  // Bind schema metadata for one Rust module.
  explicit rust_emitter(const schema& value) : model{value} {
    output += runtime;
  }
  // Emit reusable runtime declarations and direct typed model codecs.
  std::string generate() {
    line("const SRL_FIELDS: &[(&[u8], &[u8])] = &[");
    ++indent;
    for (const auto& key : model.ordered_keys) {
      std::string encoded;
      const auto size = key.size();
      const auto extra = size <= 63 ? 0 : size <= 16383 ? 1 : size <= 4194303 ? 2 : 3;
      encoded += static_cast<char>((extra << 6) | (size >> (extra * 8)));
      for (int i = extra - 1; i >= 0; --i) {
        encoded += static_cast<char>(size >> (i * 8));
      }
      encoded += key;
      line("(" + bytes(quote(key) + ":") + ", " + bytes(encoded) + "),");
    }
    --indent;
    line("];");
    for (const auto* node : model.nodes) {
      validate_identifier(model.names.at(node), std::string{keywords} + " BTreeMap ");
      if (node->type == object_type::class_type) {
        object(static_cast<const class_node&>(*node));
        continue;
      }
      const auto& value = static_cast<const enum_node&>(*node);
      const auto name = model.names.at(node);
      line("/// Stable schema ordinals with native total ordering.");
      line("#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]");
      line("#[repr(u32)]");
      open("pub enum " + name);
      for (std::size_t i = 0; i < value.enum_name_list.size(); ++i) {
        validate_identifier(pascal(value.enum_name_list[i]), keywords);
        line(pascal(value.enum_name_list[i]) + " = " + std::to_string(i) + ",");
      }
      close();
      open("impl " + name);
      std::string names = "const NAMES: &'static [&'static str] = &[";
      for (const auto& item : value.enum_name_list) {
        names += quote(item) + ",";
      }
      line(names + "];");
      line("/// Encode the native name or ordinal for this field context.");
      open("fn srl_write(self, out: &mut SrlWriter, collection: bool) -> SrlResult<()>");
      line("out.enumeration(self as usize, Self::NAMES, collection)");
      close();
      line("/// Reject undeclared enum values before construction.");
      open("fn srl_read(input: &mut SrlReader<'_>, collection: bool) -> SrlResult<Self>");
      open("match input.enumeration(Self::NAMES, collection)?");
      for (std::size_t i = 0; i < value.enum_name_list.size(); ++i) {
        line(std::to_string(i) + " => Ok(Self::" + pascal(value.enum_name_list[i]) + "),");
      }
      line("_ => Err(Error(\"Unknown enum\")),");
      close();
      close();
      close();
    }
    return output;
  }
};
} // namespace
// Generate native Rust with no runtime bindings or target SDK invocation.
std::string rust(const schema& value) {
  return rust_emitter{value}.generate();
}
} // namespace rohit::serializer::writer::native
