include_guard(GLOBAL)

# Consumers and editor integrations can refresh every registered schema through one target.
if(NOT TARGET serializer_generated_headers)
  add_custom_target(serializer_generated_headers)
endif()

# Attach real generated headers, their include directory, and generator dependencies to a target.
# Call once per target; a normal consumer build runs generation before compiling its sources.
function(serializer_generate)
  cmake_parse_arguments(PARSE_ARGV 0 arg ""
    "TARGET;OUTPUT_DIRECTORY;CONFIG;CODING_STANDARD;FORMAT_FILE;CLANG_FORMAT;GENERATOR;VISIBILITY"
    "SCHEMAS;DEPENDS")
  if(arg_UNPARSED_ARGUMENTS OR arg_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "serializer_generate: unknown arguments or missing argument values")
  endif()
  if(NOT arg_TARGET OR NOT TARGET "${arg_TARGET}" OR NOT arg_SCHEMAS)
    message(FATAL_ERROR "serializer_generate requires an existing TARGET and at least one SCHEMAS path")
  endif()
  get_target_property(imported "${arg_TARGET}" IMPORTED)
  get_target_property(aliased "${arg_TARGET}" ALIASED_TARGET)
  get_target_property(target_type "${arg_TARGET}" TYPE)
  if(imported OR aliased OR target_type STREQUAL "UTILITY")
    message(FATAL_ERROR "serializer_generate TARGET must be a local executable or library")
  endif()

  set(headers_target "${arg_TARGET}_serializer_headers")
  if(TARGET "${headers_target}")
    message(FATAL_ERROR "serializer_generate must be called once per target; list all its schemas together")
  endif()
  if(NOT arg_VISIBILITY)
    if(target_type STREQUAL "INTERFACE_LIBRARY")
      set(arg_VISIBILITY INTERFACE)
    else()
      set(arg_VISIBILITY PRIVATE)
    endif()
  endif()
  if(NOT arg_VISIBILITY MATCHES "^(PRIVATE|PUBLIC|INTERFACE)$" OR
      (target_type STREQUAL "INTERFACE_LIBRARY" AND NOT arg_VISIBILITY STREQUAL "INTERFACE"))
    message(FATAL_ERROR "serializer_generate: invalid VISIBILITY for the consuming target")
  endif()

  if(NOT arg_GENERATOR)
    set(arg_GENERATOR Serializer::serializer)
  endif()
  if(TARGET "${arg_GENERATOR}")
    get_target_property(generator_type "${arg_GENERATOR}" TYPE)
    get_target_property(generator_imported "${arg_GENERATOR}" IMPORTED)
    if(NOT generator_type STREQUAL "EXECUTABLE")
      message(FATAL_ERROR "serializer_generate GENERATOR must be an executable target or path")
    endif()
    if(CMAKE_CROSSCOMPILING AND NOT generator_imported)
      message(FATAL_ERROR "serializer_generate: pass GENERATOR pointing to a host-built Serializer when cross-compiling")
    endif()
    set(compiler "$<TARGET_FILE:${arg_GENERATOR}>")
    set(compiler_dependency "${arg_GENERATOR}")
  else()
    get_filename_component(compiler "${arg_GENERATOR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${compiler}" OR IS_DIRECTORY "${compiler}")
      message(FATAL_ERROR "serializer_generate cannot find its GENERATOR: ${compiler}")
    endif()
    set(compiler_dependency "${compiler}")
  endif()

  if(NOT arg_OUTPUT_DIRECTORY)
    set(arg_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated/${arg_TARGET}")
  endif()
  get_filename_component(output_directory "${arg_OUTPUT_DIRECTORY}" ABSOLUTE
    BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")

  set(arguments)
  set(dependencies "${compiler_dependency}" ${arg_DEPENDS})
  if(arg_CONFIG)
    get_filename_component(config "${arg_CONFIG}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${config}" OR IS_DIRECTORY "${config}")
      message(FATAL_ERROR "serializer_generate cannot find CONFIG: ${config}")
    endif()
    list(APPEND arguments --config "${config}")
    list(APPEND dependencies "${config}")
  endif()
  if(arg_CODING_STANDARD)
    list(APPEND arguments --cpp.coding_standard "${arg_CODING_STANDARD}")
  endif()
  if(arg_FORMAT_FILE)
    get_filename_component(format_file "${arg_FORMAT_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${format_file}" OR IS_DIRECTORY "${format_file}")
      message(FATAL_ERROR "serializer_generate cannot find FORMAT_FILE: ${format_file}")
    endif()
    list(APPEND arguments --cpp.format_file "${format_file}")
    list(APPEND dependencies "${format_file}")
  endif()
  if(arg_CLANG_FORMAT)
    list(APPEND arguments --cpp.clang_format "${arg_CLANG_FORMAT}")
  elseif(SERIALIZER_CLANG_FORMAT_EXECUTABLE)
    list(APPEND arguments --cpp.clang_format "${SERIALIZER_CLANG_FORMAT_EXECUTABLE}")
  endif()

  set(headers)
  foreach(schema IN LISTS arg_SCHEMAS)
    get_filename_component(input "${schema}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
      message(FATAL_ERROR "serializer_generate cannot find schema: ${input}")
    endif()
    get_filename_component(stem "${input}" NAME_WLE)
    set(header "${output_directory}/${stem}.hpp")
    # One generation rule owns each destination even when several consumers use the helper.
    set(output_identity "${header}")
    if(CMAKE_HOST_WIN32)
      string(TOLOWER "${output_identity}" output_identity)
    endif()
    string(SHA256 output_key "${output_identity}")
    get_property(output_owner GLOBAL PROPERTY "serializer_output_${output_key}")
    if(output_owner)
      message(FATAL_ERROR "serializer_generate: ${header} is already generated for ${output_owner}; use separate output directories or share its target")
    endif()
    set_property(GLOBAL PROPERTY "serializer_output_${output_key}" "${arg_TARGET}")
    list(APPEND headers "${header}")
    add_custom_command(
      OUTPUT "${header}"
      COMMAND "${CMAKE_COMMAND}" -E make_directory "${output_directory}"
      COMMAND "${compiler}" --input "${input}" --output "${header}" --language cpp
        --depfile "${header}.d" ${arguments}
      DEPENDS "${input}" ${dependencies}
      DEPFILE "${header}.d"
      COMMENT "Generating Serializer header ${stem}.hpp for ${arg_TARGET}"
      VERBATIM
    )
  endforeach()

  add_custom_target("${headers_target}" DEPENDS ${headers})
  add_dependencies("${arg_TARGET}" "${headers_target}")
  add_dependencies(serializer_generated_headers "${headers_target}")
  foreach(header IN LISTS headers)
    target_sources("${arg_TARGET}" ${arg_VISIBILITY} "$<BUILD_INTERFACE:${header}>")
  endforeach()
  target_include_directories("${arg_TARGET}" ${arg_VISIBILITY} "$<BUILD_INTERFACE:${output_directory}>")
  target_link_libraries("${arg_TARGET}" ${arg_VISIBILITY} Serializer::serializer_lib)
  set_property(TARGET "${arg_TARGET}" PROPERTY SERIALIZER_GENERATED_HEADERS "${headers}")
  set_property(TARGET "${arg_TARGET}" PROPERTY SERIALIZER_HEADERS_TARGET "${headers_target}")
endfunction()
