include_guard(GLOBAL)

# Consumers and editor integrations can refresh every registered schema through one target.
if(NOT TARGET serializer_generated_headers)
  add_custom_target(serializer_generated_headers)
endif()

# Attach real generated headers, their include directory, and generator dependencies to a target.
# Call once per target; a normal consumer build runs generation before compiling its sources.
function(serializer_generate)
  cmake_parse_arguments(PARSE_ARGV 0 arg "VERSION_POLICY_WARNINGS_AS_ERRORS"
    "TARGET;OUTPUT_DIRECTORY;CONFIG;CODING_STANDARD;FORMAT_FILE;CLANG_FORMAT;GENERATOR;VISIBILITY;VERSION_POLICY_AS_OF"
    "SCHEMAS;DEPENDS")
  if(arg_UNPARSED_ARGUMENTS OR arg_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "serializer_generate: unknown arguments or missing argument values")
  endif()
  if(NOT arg_TARGET OR NOT TARGET "${arg_TARGET}" OR NOT arg_SCHEMAS)
    message(FATAL_ERROR "serializer_generate requires an existing TARGET and at least one SCHEMAS path")
  endif()
  set(arg_TARGETS "${arg_TARGET}")
  # Keep scalar path values intact when adapting them to the shared list contract.
  string(REPLACE ";" "\\;" arg_CONFIGS "${arg_CONFIG}")
  string(REPLACE ";" "\\;" arg_OUTPUT_DIRECTORIES "${arg_OUTPUT_DIRECTORY}")
  _serializer_generate_impl()
endfunction()

# Parse each schema once for independent target/configuration pairs and own their shared build rule.
# Lists are paired by position; one target also permits the ordinary default configuration.
function(serializer_generate_variants)
  cmake_parse_arguments(PARSE_ARGV 0 arg "VERSION_POLICY_WARNINGS_AS_ERRORS"
    "CODING_STANDARD;FORMAT_FILE;CLANG_FORMAT;GENERATOR;VISIBILITY;VERSION_POLICY_AS_OF"
    "TARGETS;SCHEMAS;CONFIGS;OUTPUT_DIRECTORIES;DEPENDS")
  if(arg_UNPARSED_ARGUMENTS OR arg_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "serializer_generate_variants: unknown arguments or missing argument values")
  endif()
  _serializer_generate_impl()
endfunction()

# Share generation without re-expanding the parsed paths or reparsing scalar option values.
function(_serializer_generate_impl)
  list(LENGTH arg_TARGETS target_count)
  list(LENGTH arg_CONFIGS config_count)
  list(LENGTH arg_OUTPUT_DIRECTORIES directory_count)
  if(target_count EQUAL 0 OR NOT arg_SCHEMAS)
    message(FATAL_ERROR "serializer_generate_variants requires TARGETS and SCHEMAS")
  endif()
  if(NOT config_count EQUAL target_count AND NOT (config_count EQUAL 0 AND target_count EQUAL 1))
    message(FATAL_ERROR "serializer_generate_variants requires one CONFIGS entry per target")
  endif()
  if(NOT directory_count EQUAL 0 AND NOT directory_count EQUAL target_count)
    message(FATAL_ERROR "serializer_generate_variants requires one OUTPUT_DIRECTORIES entry per target")
  endif()
  set(unique_targets ${arg_TARGETS})
  list(REMOVE_DUPLICATES unique_targets)
  list(LENGTH unique_targets unique_target_count)
  if(NOT unique_target_count EQUAL target_count)
    message(FATAL_ERROR "serializer_generate_variants requires distinct TARGETS")
  endif()
  math(EXPR last_target "${target_count} - 1")
  foreach(index RANGE ${last_target})
    list(GET arg_TARGETS ${index} consumer)
    if(NOT TARGET "${consumer}")
      message(FATAL_ERROR "serializer_generate_variants cannot find TARGET: ${consumer}")
    endif()
    get_target_property(imported "${consumer}" IMPORTED)
    get_target_property(aliased "${consumer}" ALIASED_TARGET)
    get_target_property(target_type "${consumer}" TYPE)
    if(imported OR aliased OR target_type STREQUAL "UTILITY")
      message(FATAL_ERROR "serializer_generate TARGET must be a local executable or library")
    endif()
    if(TARGET "${consumer}_serializer_headers")
      message(FATAL_ERROR "serializer_generate must be called once per target; list all its schemas together")
    endif()
    set(visibility "${arg_VISIBILITY}")
    if(NOT visibility)
      if(target_type STREQUAL "INTERFACE_LIBRARY")
        set(visibility INTERFACE)
      else()
        set(visibility PRIVATE)
      endif()
    endif()
    if(NOT visibility MATCHES "^(PRIVATE|PUBLIC|INTERFACE)$" OR
        (target_type STREQUAL "INTERFACE_LIBRARY" AND NOT visibility STREQUAL "INTERFACE"))
      message(FATAL_ERROR "serializer_generate: invalid VISIBILITY for the consuming target")
    endif()
    set(visibility_${index} "${visibility}")
    set(headers_${index} "")
  endforeach()

  if(NOT arg_GENERATOR)
    set(arg_GENERATOR Serializer::serializer)
  endif()
  if(TARGET "${arg_GENERATOR}")
    get_target_property(generator_type "${arg_GENERATOR}" TYPE)
    get_target_property(generator_imported "${arg_GENERATOR}" IMPORTED)
    if(NOT generator_type STREQUAL "EXECUTABLE")
      message(FATAL_ERROR "serializer_generate GENERATOR must be an executable target or path")
    endif()
    if(CMAKE_CROSSCOMPILING AND NOT generator_imported)
      message(FATAL_ERROR "serializer_generate: pass GENERATOR pointing to a host-built Serializer when cross-compiling")
    endif()
    set(compiler "$<TARGET_FILE:${arg_GENERATOR}>")
    set(compiler_dependency "${arg_GENERATOR}")
  else()
    get_filename_component(compiler "${arg_GENERATOR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${compiler}" OR IS_DIRECTORY "${compiler}")
      message(FATAL_ERROR "serializer_generate cannot find its GENERATOR: ${compiler}")
    endif()
    set(compiler_dependency "${compiler}")
  endif()

  set(output_directories)
  foreach(index RANGE ${last_target})
    if(directory_count EQUAL 0)
      list(GET arg_TARGETS ${index} consumer)
      set(directory "${CMAKE_CURRENT_BINARY_DIR}/generated/${consumer}")
    else()
      list(GET arg_OUTPUT_DIRECTORIES ${index} directory)
    endif()
    get_filename_component(output_directory "${directory}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
    list(APPEND output_directories "${output_directory}")
  endforeach()

  set(arguments)
  if(arg_VERSION_POLICY_AS_OF)
    list(APPEND arguments --version-policy-as-of "${arg_VERSION_POLICY_AS_OF}")
  endif()
  if(arg_VERSION_POLICY_WARNINGS_AS_ERRORS)
    list(APPEND arguments --version-policy-warnings-as-errors)
  endif()
  set(dependencies "${compiler_dependency}" ${arg_DEPENDS})
  foreach(configuration IN LISTS arg_CONFIGS)
    get_filename_component(config "${configuration}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${config}" OR IS_DIRECTORY "${config}")
      message(FATAL_ERROR "serializer_generate cannot find CONFIG: ${config}")
    endif()
    list(APPEND arguments --config "${config}")
    list(APPEND dependencies "${config}")
  endforeach()
  if(arg_CODING_STANDARD)
    list(APPEND arguments --cpp.coding_standard "${arg_CODING_STANDARD}")
  endif()
  if(arg_FORMAT_FILE)
    get_filename_component(format_file "${arg_FORMAT_FILE}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${format_file}" OR IS_DIRECTORY "${format_file}")
      message(FATAL_ERROR "serializer_generate cannot find FORMAT_FILE: ${format_file}")
    endif()
    list(APPEND arguments --cpp.format_file "${format_file}")
    list(APPEND dependencies "${format_file}")
  endif()
  if(arg_CLANG_FORMAT)
    list(APPEND arguments --cpp.clang_format "${arg_CLANG_FORMAT}")
  elseif(SERIALIZER_CLANG_FORMAT_EXECUTABLE)
    list(APPEND arguments --cpp.clang_format "${SERIALIZER_CLANG_FORMAT_EXECUTABLE}")
  endif()

  set(headers)
  foreach(schema IN LISTS arg_SCHEMAS)
    get_filename_component(input "${schema}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${input}" OR IS_DIRECTORY "${input}")
      message(FATAL_ERROR "serializer_generate cannot find schema: ${input}")
    endif()
    get_filename_component(stem "${input}" NAME_WLE)
    set(schema_headers)
    set(output_arguments)
    foreach(index RANGE ${last_target})
      list(GET output_directories ${index} output_directory)
      list(GET arg_TARGETS ${index} consumer)
      set(header "${output_directory}/${stem}.hpp")
      # One shared rule owns each destination, even when several consumers build in parallel.
      set(output_identity "${header}")
      if(CMAKE_HOST_WIN32)
        string(TOLOWER "${output_identity}" output_identity)
      endif()
      string(SHA256 output_key "${output_identity}")
      get_property(output_owner GLOBAL PROPERTY "serializer_output_${output_key}")
      if(output_owner)
        message(FATAL_ERROR "serializer_generate: ${header} is already generated for ${output_owner}; use separate output directories or share its target")
      endif()
      set_property(GLOBAL PROPERTY "serializer_output_${output_key}" "${consumer}")
      list(APPEND schema_headers "${header}")
      list(APPEND headers_${index} "${header}")
      list(APPEND output_arguments --output "${header}")
    endforeach()
    list(GET schema_headers 0 first_header)
    list(APPEND headers ${schema_headers})
    add_custom_command(
      OUTPUT ${schema_headers}
      COMMAND "${CMAKE_COMMAND}" -E make_directory ${output_directories}
      COMMAND "${compiler}" --input "${input}" ${output_arguments} --language cpp
        --depfile "${first_header}.d" ${arguments}
      DEPENDS "${input}" ${dependencies}
      DEPFILE "${first_header}.d"
      COMMENT "Generating Serializer header ${stem}.hpp for ${arg_TARGETS}"
      VERBATIM
    )
  endforeach()

  list(GET arg_TARGETS 0 first_target)
  set(batch_target "${first_target}_serializer_batch_headers")
  add_custom_target("${batch_target}" DEPENDS ${headers})
  foreach(index RANGE ${last_target})
    list(GET arg_TARGETS ${index} consumer)
    list(GET output_directories ${index} output_directory)
    set(headers_target "${consumer}_serializer_headers")
    add_custom_target("${headers_target}")
    add_dependencies("${headers_target}" "${batch_target}")
    add_dependencies("${consumer}" "${headers_target}")
    add_dependencies(serializer_generated_headers "${headers_target}")
    foreach(header IN LISTS headers_${index})
      target_sources("${consumer}" ${visibility_${index}} "$<BUILD_INTERFACE:${header}>")
    endforeach()
    target_include_directories("${consumer}" ${visibility_${index}} "$<BUILD_INTERFACE:${output_directory}>")
    target_link_libraries("${consumer}" ${visibility_${index}} Serializer::runtime)
    set_property(TARGET "${consumer}" PROPERTY SERIALIZER_GENERATED_HEADERS "${headers_${index}}")
    set_property(TARGET "${consumer}" PROPERTY SERIALIZER_HEADERS_TARGET "${headers_target}")
  endforeach()
endfunction()
