# Keep dependency discovery identical for source builds and installed static consumers.
set(serializer_compression_libraries)
if(SERIALIZER_WITH_ZSTD)
  find_package(zstd CONFIG REQUIRED)
  if(TARGET zstd::libzstd_static)
    list(APPEND serializer_compression_libraries zstd::libzstd_static)
  else()
    list(APPEND serializer_compression_libraries zstd::libzstd_shared)
  endif()
endif()
if(SERIALIZER_WITH_LZ4)
  find_package(lz4 CONFIG REQUIRED)
  list(APPEND serializer_compression_libraries LZ4::lz4)
endif()
if(SERIALIZER_WITH_ZLIB)
  find_package(ZLIB REQUIRED)
  list(APPEND serializer_compression_libraries ZLIB::ZLIB)
endif()
