include_guard(GLOBAL)

# Generate a self-contained Java compilation unit with tracked schema/config dependencies.
function(serializer_generate_java)
  cmake_parse_arguments(PARSE_ARGV 0 ARG "" "TARGET;SCHEMA;OUTPUT;CONFIG;GENERATOR" "DEPENDS")
  if(ARG_UNPARSED_ARGUMENTS OR ARG_KEYWORDS_MISSING_VALUES OR NOT ARG_TARGET OR NOT ARG_SCHEMA OR NOT ARG_OUTPUT)
    message(FATAL_ERROR "serializer_generate_java requires TARGET, SCHEMA, OUTPUT and optional CONFIG/GENERATOR/DEPENDS")
  endif()
  if(TARGET "${ARG_TARGET}")
    message(FATAL_ERROR "Java generation target already exists: ${ARG_TARGET}")
  endif()
  get_filename_component(schema "${ARG_SCHEMA}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
  get_filename_component(output "${ARG_OUTPUT}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
  get_filename_component(directory "${output}" DIRECTORY)
  if(NOT EXISTS "${schema}" OR IS_DIRECTORY "${schema}")
    message(FATAL_ERROR "Java schema does not exist: ${schema}")
  endif()
  if(NOT output MATCHES "\\.java$")
    message(FATAL_ERROR "Java generation OUTPUT must end in .java")
  endif()
  set(identity "${output}")
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${identity}" identity)
  endif()
  string(SHA256 output_key "${identity}")
  get_property(owner GLOBAL PROPERTY "serializer_output_${output_key}")
  if(owner)
    message(FATAL_ERROR "Java output already belongs to ${owner}: ${output}")
  endif()
  set_property(GLOBAL PROPERTY "serializer_output_${output_key}" "${ARG_TARGET}")
  set(arguments --input "${schema}" --output "${output}" --language java)
  set(dependencies "${schema}" ${ARG_DEPENDS})
  if(ARG_CONFIG)
    get_filename_component(config "${ARG_CONFIG}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    list(APPEND arguments --config "${config}")
    list(APPEND dependencies "${config}")
  endif()
  if(ARG_GENERATOR)
    if(TARGET "${ARG_GENERATOR}")
      get_target_property(generator_type "${ARG_GENERATOR}" TYPE)
      get_target_property(generator_imported "${ARG_GENERATOR}" IMPORTED)
      if(NOT generator_type STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "Java GENERATOR target must be executable")
      endif()
      if(CMAKE_CROSSCOMPILING AND NOT generator_imported)
        message(FATAL_ERROR "Cross builds require a host GENERATOR executable")
      endif()
      set(generator "$<TARGET_FILE:${ARG_GENERATOR}>")
    else()
      get_filename_component(generator "${ARG_GENERATOR}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    endif()
    list(APPEND dependencies "${ARG_GENERATOR}")
  elseif(TARGET Serializer::serializer)
    get_target_property(generator_imported Serializer::serializer IMPORTED)
    if(CMAKE_CROSSCOMPILING AND NOT generator_imported)
      message(FATAL_ERROR "Cross builds require a host GENERATOR executable")
    endif()
    set(generator "$<TARGET_FILE:Serializer::serializer>")
    list(APPEND dependencies Serializer::serializer)
  else()
    message(FATAL_ERROR "Serializer::serializer or a host GENERATOR is required")
  endif()
  add_custom_command(OUTPUT "${output}"
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${directory}"
    COMMAND "${generator}" ${arguments}
    DEPENDS ${dependencies}
    COMMENT "Generating Java schema ${output}"
    VERBATIM)
  add_custom_target("${ARG_TARGET}" DEPENDS "${output}")
  if(NOT TARGET serializer_generated_java)
    add_custom_target(serializer_generated_java)
  endif()
  add_dependencies(serializer_generated_java "${ARG_TARGET}")
endfunction()
